### ISSUE TITLE
Minimum .Net version

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustSaying#101]
Is is advisable to increase the .Net build version to 4.5.0?
Will this adversely impact any clients?
This would be required before doing any `async` handlers, but can be done as a separate change.

**Comment by payman81** [comment]
@AnthonySteele Since that needs a major version change, I recommend keeping it in a remote branch until we're ready to release. This way, we can release minor versions without introducing breaking change.

**Comment by AnthonySteele** [comment]
good point, increasing the required .Net version is potentially breaking change and requires a major version number bump. 

I have tried out compiling JustSaying for .Net 4.5, and it also requires removing and re-adding several nuget packages to reference the .Net 4.5 version of these in order to use the `async` methods. Particularly the `AWSSDK` package. 

I would suggest doing all desired package version updates first, before splitting that branch off so as to make it more granular & easier to follow.

**Comment by AnthonySteele** [comment]
It's hard to do the package updates before changing to .Net 4.5. A couple of minor things are re-inforcing to greater effect here
- [The currently used version of JustBehave](https://www.nuget.org/packages/JustBehave/0.57.0) targets .Net but is locked to 1 specific old version of AutoFixture. This is fixed in the latest version of JustBehave, but
- The current version of JustBehave targets .Net 4.5.1 and up.

**Comment by AnthonySteele** [comment]
This is done, AFAIK
