### ISSUE TITLE
Change error logging from trace to warning/error when messages are deleted

### ISSUE THREAD

**Issue by namado** [justeat/JustSaying#1077]
**Describe the bug**
When the message `Subject` is empty or it doesn't match the `Type` subject the code falls through an exception that ends up deleting the message.

When this happens there is only a `Trace` level logging to account for the process.
As this can happen in production environments having that level of logging is not feasible.
Can this be changed to either `Warning` or `Error` ?

https://github.com/justeat/JustSaying/blob/4b1a15dad385abf1758e185f74744ac43ddf6ed1/src/JustSaying/AwsTools/MessageHandling/Dispatch/MessageDispatcher.cs#L84-L92

**Steps To reproduce**
Create a message without `Subject` (`AWS` states its optional), the message handler fails and deletes the message, leaving no logs on non `Verbose` logging settings

**Expected behaviour**
A `Warning` or `Error` type log is created.

**Actual behaviour**
A `Trace` log is created.

**System information:**
 - OS: Windows 10
 - Library Version 7.0.0
 - .NET version 6.0

**Additional context**
Even though `AWS` states that the `Subject` is optional I'm not asking to change the current validation logic, only the logging level.

![image](https://user-images.githubusercontent.com/57901368/197239624-9c82b130-69b1-4c2f-af37-2b435d2c83b0.png)

**Comment by adammorr** [comment]
Addressed by https://github.com/justeat/JustSaying/pull/1101
