### ISSUE TITLE
unit tests failing

### ISSUE THREAD

**Issue by theburningmonk** [justeat/JustSaying#129]
Just forked the repo, ran tests and couple of them are failing out of the box. Ran the entire test suite a few times and it seems some tests fail due to timing-related issue, though there seems to be some repeat offenders:

![image](https://cloud.githubusercontent.com/assets/546969/11567495/2d24a47c-99df-11e5-8ae7-7ba107782243.png)

![image](https://cloud.githubusercontent.com/assets/546969/11567941/8f0909ec-99e1-11e5-89a5-b6080de83c87.png)

![image](https://cloud.githubusercontent.com/assets/546969/11568264/17146808-99e3-11e5-9a31-2853f148e973.png)

**Comment by payman81** [comment]
Integration tests are flaky due to lack of loopback/in-memory transport. The timing issue exist as long as we use real aws topics/queues for tests. There's been several half attempts to address this but none that can be introduced without a major redesign. Ideas/PRs are welcome.

**Comment by theburningmonk** [comment]
when I was working on the PR for making the SQS receive loop async I noticed that some of the timing-sensitive tests (not only the integration cases) that fail from time to time seem to be related to the way you wait synchronously (by putting the current thread to sleep), which can impact the execution of handler code. 

In the async version this became more noticeable because all async callbacks are executed against the ThreadPool (which unless otherwise specified, starts with 1 thread) so if that thread is being blocked by the observation code (say, `Patiently.VerifyExpectation`) then the async callbacks won't get a chance to execute (until additional threads are made available and it gets a slot to run, how and when this happens is a runtime decision the ThreadPool makes based on its hill-climbing algo and based on my observation makes a few of the tests fail about 4/5 times).
