### ISSUE TITLE
Fluent API does not allow to register publishers without having handlers

### ISSUE THREAD

**Issue by dariusdamalakas** [justeat/JustSaying#136]
Not all of our services need to subscribe to bus messages, some of them just need to publish.

Below code does not compile, unless `WithMessageHandler` is uncommented.

````C#
justSaying
    .WithSqsTopicSubscriber()
    .IntoQueue(busNamingConvention.QueueName())
    //.WithMessageHandler<SimpleBusMessage>(handlerResolver)
    .WithSqsMessagePublisher<UnscheduleTimeout>(c => c.QueueName = "<queueName>"));
````

**Comment by payman81** [comment]
If all you're doing is publish then you don't need to register a SqsTopicSubscriber or a queue name. This should be sufficient:
````C#
justSaying
    .WithSqsMessagePublisher<UnscheduleTimeout>(c => c.QueueName = "<queueName>"));
````

If the naming convention is the problem then we can address that issue separately.

**Comment by dariusdamalakas** [comment]
@payman81 , doh, that makes perfect sense. No, this is all fine as I see it. Thanks alot!
