### ISSUE TITLE
Don't need the "delete message if cannot deserialise" logic in SqsNotificationListener.cs

### ISSUE THREAD

**Issue by brainmurphy** [justeat/JustSaying#138]
i.e. in https://github.com/justeat/JustSaying/blob/master/JustSaying.AwsTools/SqsNotificationListener.cs#L258

If you receive a message, you must be able to deserialise it.

**Comment by slang25** [comment]
Yeah, that comes as a shock. I think it should leave the messages in there so that your alerting can let you know there's an issue.
