### ISSUE TITLE
AWS SDK version 3

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustSaying#149]
We use AWS SWK version `2.3.x` throughout, but the latest stable version of the AWS SDK is `3.1.x`. 

At some stage we will want to take on the breaking changes of major version number 3. One thing that will be important is [DotNet Core support, which will land in version `3.2`](https://blogs.aws.amazon.com/net/post/Tx2JLGUF5YRULNK/AWS-SDK-for-NET-Refresh-for-ASP-NET-5) which is [currently in beta](https://www.nuget.org/packages/AWSSDK.Core/3.2.2-beta)

Are there any other benefits of using version 3.x? I know it is much more modular, so there will be more packages but a smaller total size of binaries used. Are there any features that are not present in the version 2 packages that are useful?

**Comment by payman81** [comment]
I had a look at their commits and couldn't find any change to SNS SQS clients since version 2.3.x. https://github.com/aws/aws-sdk-net/commits/master

**Comment by AnthonySteele** [comment]
So this suggests that the update to 3.x should be a) easy, but b) not that useful until we look at DotNet Core ?

**Comment by payman81** [comment]
@AnthonySteele Is there any benefit to update the SDK right now? Or should we update when we're looking at DotNet Core?

**Comment by AnthonySteele** [comment]
It would be pro-active to update to AWSSDK `3.x` soon, it will be necessary when we look at  DotNet Core.

**Comment by normj** [comment]
One subtle advantage you might find in 3.1.x version of the AWS SDK for .NET is we no longer update the AssemblyVersion for every release. It is currently locked to version 3.1 and 3.2 for the coreclr beta release. This was done to help class libraries like this not need to do a recompile for every new release of the SDK. The AssemblyFileVersion is still always updated for every release but that version is just for display purposes.

**Comment by payman81** [comment]
That is very useful @normj. Thanks for that.

**Comment by dariusdamalakas** [comment]
[http://blogs.aws.amazon.com/net/post/TxTXAQT3ZZERZ7/AWS-SDK-for-NET-Version-2-Status](in AWS Blog) they say last new features will be added on 8/1/2016, and then no more changes, only critical issue fixes.

There's a nice migration guide [here](http://docs.aws.amazon.com/AWSSdkDocsNET/V3/DeveloperGuide/net-dg-migration-guide-v3.html).  I understand if we first update to latest AWS v2 SDK, and solve all warnings, transition to v3 should be smooth.

**Comment by Liewe** [comment]
I ded a pullrequest for this: https://github.com/justeat/JustSaying/pull/209

**Comment by AnthonySteele** [comment]
:+1: great. We will look at trialing and merging this after the next release

**Comment by slang25** [comment]
Fixed in v5 rc1
