### ISSUE TITLE
Appveyor and NUnit console issue

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustSaying#162]
In the Appveyor output we get this text

```
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.
 
Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8009 ( Net 3.5 )
 
ProcessModel: Default    DomainUsage: Multiple
Execution Runtime: net-3.5
```

This is of course wrong, we are on .Net version 4.5.2. 

[We are experiencing this issue](http://help.appveyor.com/discussions/problems/1737-tests-fail-to-run-with-weird-error). This affects some `async` tests - we have had spurious fails on appveyor of tests that pass locally, and we likely have spurious passes (i.e. if they started failing locally, appveyor would not notice).

Using NUnit 3.0 may be the answer according so some discussions.  We don't use NUnit 3.0 yet.
JustSaying my be a good trial for NUnit 3.0?

**Comment by dariusdamalakas** [comment]
Just a note NUnit 3.0. - There's a slight syntax change to `Assert.Throws` in that it does not support async code, instead they have added `Assert.ThrowsAsync`. I am ok with upgrade to NUnit 3.0, should be no major issues.

**Comment by AnthonySteele** [comment]
Yep, I believe that the `Assert.AreEqual` syntax is also deprecated in favour of `Assert.That`. We can update to deal with these minor issues.

**Comment by AnthonySteele** [comment]
We are on NUnit 3.0 now.
