### ISSUE TITLE
Async JustBehave tests are not reliable

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustSaying#171]
In all the `JustSaying.AwsTools.UnitTests.MessageHandling.SqsNotificationListener.WhenMessageHandlingXXX` tests, I can change `Monitor.ReceivedWithAnyArgs().HandleException` to `Monitor.DidNotReceiveWithAnyArgs().HandleException` and vice versa and the test still passes. 

This means that they are not actually testing anything. It is likely that the `async` has gone wrong, something is declaring success too early, instead of awaiting actual pass or fail.

I have also had issues on a PR with tests that pass locally and fail on Appveyor, after emitting so much output that the Appveyor build results cannot be viewed.

The combination of JustBehave and `await Patiently.VerifyExpectationAsync` seems to be a bad one.

**Comment by AnthonySteele** [comment]
Further investigation in `JustBehave`:
1) There is a `AsyncBehaviourTestBase` for when the `When` has signature ` protected override async Task When()`. We should use this?

The `[Then]` attribute derives from `NUnit.TestAttribute`, so should work when it's async.

We could also remove `JustBehave` from `JustSaying` entirely, but that's 63 tests to change. Do we want to embark on that?

**Comment by AnthonySteele** [comment]
I thought about it a bit more, and this is how I see it:

Suppose we have an async '[Then]` method that tests that an exception was not thrown. How long would you wait to see if it happens? In the code as it stands, this would succeed the first time around the retry loop, and not wait any more. If the exception is thrown later it will not be noticed and the test will spuriously pass. The results will vary if a different `[Then]` method has already delayed things due to waiting for a pass on other conditions.

The way to make these tests work reliably would be to make the `[When]` method only exit when the state is ready to test, and have no asynchrony or delay in `[Then]` methods.

The collection of `[Then]` methods would represent a set of conditions that you want to test *at a point in time*, and it's the role of the `When` to get into this state, using async if need be.

**Comment by petemounce** [comment]
So something in the base class waits for When's Task to complete before proceeding?

**Comment by AnthonySteele** [comment]
Should o, if you inherit from [AsyncBehaviourTest](https://github.com/justeat/JustBehave/blob/master/src/JustBehave/AsyncBehaviourTest.cs)  (see also [AsyncBehaviourTestBase](https://github.com/justeat/JustBehave/blob/master/src/JustBehave/AsyncBehaviourTestBase.cs)

**Comment by GraemeF** [comment]
That would mean `[When]` must return a task? Might it be clearer/simpler to let the implementation of `[When]` wait for whatever it wants before returning.

**Comment by brainmurphy** [comment]
If it's easier to write a good test without using JustBehave, I'm in favour of that.

**Comment by AnthonySteele** [comment]
@brainmurphy could do, but there are 63 tests that use `JustBehave`. We're not going to change them all this week.

**Comment by AnthonySteele** [comment]
Then should  signal that the work is done, i.e something like:

````csharp

    public class SignallingHandler<T> : IHandler<T>
    {
        private readonly TaskCompletionSource<bool> _executedSignal;
        private readonly Func<T, bool> _resultFn;

        public SignallingHandler(TaskCompletionSource<bool> executedSignal, Func<T, bool> resultFn)
        {
            _executedSignal = executedSignal;
            _resultFn = resultFn;
        }

        public bool Handle(T message)
        {
            _executedSignal.SetResult(true);
            return _resultFn(message);
        }
    }


        public async Task Then()
        {
            Func<GenericMessage, bool> success = m => true;
            var tcs = new TaskCompletionSource<bool>();
            var handler = new SignallingHandler<GenericMessage>(tcs, success);

            // do something with the handler on a thread
            var running = Task.Run(async () => 
            {
                await Task.Delay(1000);
                handler.Handle(new GenericMessage());
            });

            // wait until the signal is raised
            await tcs.Task;
        }

```

**Comment by AnthonySteele** [comment]
Has been done
