### ISSUE TITLE
`WithSnsMessagePublisher` is non-deterministic

### ISSUE THREAD

**Issue by gerrod** [justeat/JustSaying#213]
Hi there - I've just started looking at JustSaying for use at work, and have spotted a few potential bugs in `WithSnsMessagePublisher` - however I'm not sure if these are actually bugs, or if they're intended behavior.

Here's the code, marked up for reference:

```
public IHaveFulfilledPublishRequirements WithSnsMessagePublisher<T>() where T : Message
{
    Log.Info("Adding SNS publisher");

    // ---== #1: MAYBE A BUG ==------------------------
    // _subscriptionConfig.Topic is set here, but it is not the topic that is used to create
    // the SnsTopicByName.
    _subscriptionConfig.Topic = GetMessageTypeName<T>();
    // ------------------------------------------------

    var namingStrategy = GetNamingStrategy();
    Bus.SerialisationRegister.AddSerialiser<T>(_serialisationFactory.GetSerialiser<T>());

    // ---== #2: MAYBE A BUG ==------------------------
    // _subscriptionConfig.BaseTopicName will only be set if you've previously added an
    // SnsSubscriber with a topic.
    var topicName = namingStrategy.GetTopicName(_subscriptionConfig.BaseTopicName, GetMessageTypeName<T>());
    // ------------------------------------------------

    foreach (var region in Bus.Config.Regions)
    {
        var eventPublisher = new SnsTopicByName(
            topicName,
            _awsClientFactoryProxy.GetAwsClientFactory().GetSnsClient(RegionEndpoint.GetBySystemName(region)),
            Bus.SerialisationRegister);

        if (!eventPublisher.Exists())
            eventPublisher.Create();

        Bus.AddMessagePublisher<T>(eventPublisher, region);
    }

    // ---== #3: LIKELY A BUG ==-----------------------
    // The topic logged here should be "topicName" not "_subscriptionConfig.Topic".
    // Alternatively, _subscriptionConfig.Topic should possibly be updated to be topicName.
    Log.Info(string.Format("Created SNS topic publisher - Topic: {0}", _subscriptionConfig.Topic));
    // ------------------------------------------------

    return this;
}
```

Hopefully numbers 1 and 3 are self explanatory; here's some sample code that yields the problem referred to by number 2:

```
CreateMeABus
    .InRegion(RegionEndpoint.APSoutheast2.SystemName)
    .WithNamingStrategy(() => pantsNamingStrategy)

    // Since no topic subscribers have been registered in the fluent pipeline, the config passed
    // to `GetQueueName` in the naming strategy will have a null BaseQueueName
    .WithSnsMessagePublisher<HotPantsMessage>()

    .WithSqsTopicSubscriber("hot")
    .IntoQueue("pants")
    .WithMessageHandler(hotPantsHandler)

    // Since a topic subscriber has been registered in the fluent pipeline, the config passed to
    // `GetQueueName` in the naming strategy will have "hot" passed as the BaseQueueName
    .WithSnsMessagePublisher<NoPantsMessage>();
```

**Comment by dariusdamalakas** [comment]
@gerrod , ok, so for the 2nd case, what is the resulting topic that is created in your code, and what is the expected here? 

I don't see any issues so far, depending on what `pantsNamingStrategy` is doing, but by default the topic name will be `HotPants`. 

P.s. I agree the fluent interface might be confusing sometimes. Potentially we could update this.

**Comment by gerrod** [comment]
Hi @dariusdamalakas - thanks for the reply!

Here's a more fully fledged (mythical) example. The thing that looks like a bug to me is that you have to configure the publisher at a certain point in the pipeline if you want to influence the `baseTopicName` parameter passed to `GetTopicName` in the naming strategy. Which means either (a) you have to execute steps in the "correct" order when configuring the bus (but the fluent interface does not enforce this); (b) the naming strategy has to know _who_ is requesting the topic name in order to work out what to return; or (c) the naming strategy has to ignore the `topicName` parameter since it's unreliable.

    public class Order : Message {}

    public class OrderNamingStrategy : INamingStrategy
    {
        public string GetTopicName(string topicName, string messageType)
        {
            return $"{topicName}-{messageType}";
        }

        // ----- 8< -----
    }

    public class OrderAcceptedMessageHandler : IHandler<Order>
    {
        public bool Handle(Order message)
        {
            return true;
        }
    }

    public class Broker() 
    {
        public void ConnectToBus()
        {
            var namingStrategy = new OrderNamingStrategy();

            // Publisher here is no good because it publishes on the wrong topic
            CreateMeABus
                .InRegion(RegionEndpoint.APSoutheast2.SystemName)
                .WithNamingStrategy(() => namingStrategy)

                // topic for publisher is "-order" - there's no way for me to change this here.
                .WithSnsMessagePublisher<Order>()       
                .WithSqsTopicSubscriber("accepted")
                .IntoQueue("order")

                // topic for subscription is "accepted-order"
                .WithMessageHandler<Order>(new OrderAcceptedMessageHandler());

            // Publisher here is correct
            CreateMeABus
                .InRegion(RegionEndpoint.APSoutheast2.SystemName)
                .WithNamingStrategy(() => namingStrategy)

                .WithSqsTopicSubscriber("accepted")
                .IntoQueue("order")

                // topic for subscription is "accepted-order"
                .WithMessageHandler<Order>(new OrderAcceptedMessageHandler())

                // topic for publisher is "accepted-order"
                .WithSnsMessagePublisher<Order>();
        }    
    }

As an aside - we're not explicitly relying on this behaviour :-) it was just something I found while prototyping to work out how everything fits together.

**Comment by payman81** [comment]
You implementation of ````INamingStrategy```` i.e. ````OrderNamingStrategy```` is using 'topicName' which is set as you rightly pointed out during ````.WithSqsTopicSubscriber(...)```` which results in the inconsistency you mentioned.
But the default implementation of ````INamingStrategy```` i.e. [DefaultNamingStrategy](https://github.com/justeat/JustSaying/blob/master/JustSaying/DefaultNamingStrategy.cs#L16) that is shipped with JustSaying doesn't do that therefore it remains consistent regardless of the order you define subscribers/publishers.
I suggest that you use a naming convention for your topics that is independent of your subscribers.

**Comment by gerrod** [comment]
Hi @payman81 - yep, I can easily work around this by either:

a) using the default naming strategy;
b) by ignoring the `topicName` as its passed to the naming strategy,; or
c) making sure I execute the configuration in the "correct" order to make the topic name more predictable.

I guess my argument is that the order of the configuration shouldn't matter.

The easiest work-around to allow this that I can see would be to have an optional parameter on `WithSnsMessagePublisher` which configures the `baseTopicName` on the configuration object; e.g.:

        CreateMeABus
            .InRegion(RegionEndpoint.APSoutheast2.SystemName)
            .WithNamingStrategy(() => namingStrategy)

            // Allow an overload to set the baseTopicName on the configuration object
            .WithSnsMessagePublisher<Order>("accepted")       

            .WithSqsTopicSubscriber("accepted")
            .IntoQueue("order")

            // topic for subscription is still "accepted-order"
            .WithMessageHandler<Order>(new OrderAcceptedMessageHandler());

Otherwise the `topicName` passed to `GetNamingStrategy` is unreliable - so (as you've said) the best the naming strategy could do would be to return a topic name that's independent of the `topicName` parameter. But if that's the case, what's the purpose of this parameter?

Happy to submit a PR if you like, but given that both yourself and @dariusdamalakas don't seem to think this is a bug I'm also happy to let is slide. As I originally stated, I don't know all of the intentions behind the code so this could be expected behaviour.

**Comment by dariusdamalakas** [comment]
@gerrod , I see the issue. For SQS publisher here's how the queue name can be overriden:

````
    .WithSqsMessagePublisher<PrintToConsole>(config => config.QueueName = "Queue1")
````

I have never ran into issues like this, but thats because we specify handlers first, and then publishers. But your scenario is valid since fluent interface allows this. I am still not fully sure that your suggested overload is absolutely necessary, although i kinda like it, as it allows to override to which topic messages are being published. 

> so (as you've said) the best the naming strategy could do would be to return a topic name that's independent of the topicName parameter.

It really depends how you want to configure. We use topic per message type naming, and single queue per service. As far as I know, JustEat uses topic per message and queue per message. So there are different options here.
