### ISSUE TITLE
IHandlerAsync's Handle method name does not fit in with convention for async methods

### ISSUE THREAD

**Issue by codedemonuk** [justeat/JustSaying#217]
The `Task<bool> Handle( T message)` method of the `IHandlerAsync<in T>` interface should be renamed `Task<bool> HandleAsync(T message)` to fit in with the .Net frameworks convention for async method names.

**Comment by AnthonySteele** [comment]
I find that convention useful when there is a choice of related methods, especially with different return types, e.g. there is `public void Foo()` and `public Task FooAsync()`. 

I do not find it useful when there is only one method and it is clear from context that it is async.
