### ISSUE TITLE
Support message handler locator

### ISSUE THREAD

**Issue by cosminonea** [justeat/JustSaying#25]
If you have a handler that depends on transient disposable objects, like db connections or sessions etc, you need to get hold of the IoC container in your handler and manually resolve and release those dependencies. 

This behaviour should be pushed into JustSaying as it is generic enough. 
So we need to support something like:

```
..WithMessageHandler<OrderAccepted>(new HandlerResolver())
```

**Comment by dariusdamalakas** [comment]
This is done, issue closed?

**Comment by ILikePies** [comment]
yes, thanks @dariusdamalakas

**Comment by payman81** [comment]
@dariusdamalakas we are testing this feature in production. Once we have good results I'll close the issue.

**Comment by ILikePies** [comment]
@payman81 - I thought you were on holiday ;)
Opening as per @payman81 's comment, although tomorrow morning we'll know for sure.

**Comment by ILikePies** [comment]
Confirmed the feature is stable.
