### ISSUE TITLE
Release a version with AWSSDK 3 

### ISSUE THREAD

**Issue by zorrme** [justeat/JustSaying#255]
Can we please have a nuget package (pre-release) with ASW SDK V3

**Comment by slang25** [comment]
We have it in our develop branch which will become version 5, we plan on making some breaking changes in version 5, so know that if we did this you would have to change your code when we come out of preview.

We aren't running this version anywhere yet, so be aware you'll be the guinea pig  🐹 I'm certainly up for doing a pre-release.

**Comment by zorrme** [comment]
I do not mind the changes later, but right now I have included your develop branch in my solution. A pre-release nuget packages would definitely be better. I cannot include the current version because I use AWSSDK 3, which conflicts with AWSSDK 2.

**Comment by AnthonySteele** [comment]
We are homing to release when the version of AWS SDK 3.x that supports .net core comes out of beta.
Unfortunately we don't know when that will be.

**Comment by zorrme** [comment]
Can we please do a pre-release nuget package with the caveat that API might change drastically. I just need a working package with aws sdk v3.

**Comment by slang25** [comment]
I will get around to this, but don't let me or anyone block you, AppVeyor is free & myget.org is free

**Comment by jorbor** [comment]
@zorrme I packaged a pre-release here, but be aware it's versioned as 4.0.1-develop: https://www.myget.org/feed/Details/justsaying

**Comment by slang25** [comment]
Thanks @jorbor 😄 
We will publish a pre-release of v5 at some point on nuget.org, we are just working on finishing .NET Core support and adding cakebuild: https://github.com/slang25/JustSaying/tree/AnthonySteele-netcore
^ once this does the basics of producing the right artifact and merged, we'll kick off a v5 beta. We intend to keep it in beta while AWSSDK is in beta (which we don't know when will release) and we will likely make some breaking changes during this period.

**Comment by zorrme** [comment]
Thanks @jorbor, but I cannot see those packages. Are they public ?

**Comment by jorbor** [comment]
Oh sure, that might help, eh? :)

Try adding nuget source: https://www.myget.org/F/justsaying/api/v2, then
> Install-Package JustSaying -Version 4.0.1-develop

**Comment by zorrme** [comment]
Hmm... thanks, but I also need JustSaying-tools package, and that package still have awssdk v2 dependency.

**Comment by jorbor** [comment]
> Install-Package JustSaying.Tools -Version 4.0.1-develop

doesn't work?

**Comment by zorrme** [comment]
It does, but it has awssdk v2 dependency.

**Comment by jorbor** [comment]
Give `4.1.9-develop` a try.

**Comment by zorrme** [comment]
Awesome, thanks a lot @jorbor

**Comment by zorrme** [comment]
@jorbor, the packages were fine. But they do not work as expected, i.e. there is not SQS trigger. I have gone back to including the whole source code for now.

**Comment by dariusdamalakas** [comment]
#292 fixes this, should this be closed?

**Comment by slang25** [comment]
Closing in favor of #292
