### ISSUE TITLE
Can JustSaying be used with akka.net ?

### ISSUE THREAD

**Issue by zorrme** [justeat/JustSaying#258]
If yes, do we have any example ?

**Comment by slang25** [comment]
@zorrme what is your use case? You could publish a message via JustSaying in an actor, or you could subscribe to messages with just saying and send them to actors, sort of forwarding them.

**Comment by zorrme** [comment]
I am trying to use akka.net and JustSaying in an asp.net mvc web app for some background processing. Right now I have configured JustSaying event bus in an akka.net actor's pre-start and am sending a message to another actor upon receiving a message in JustSaying. I am hoping this approach will be efficient  and will not slow down my webapp ?

**Comment by slang25** [comment]
I would have done the bus configuring in the ```Startup.cs```/```App_Start```/```Global.asax```, but I don't know akka.net well enough, I think the JustSaying bus isn't optimised for short lived situations, it does some api calls to ensure stuff is created, if you are doing this on each publish I'm not sure how well the will work under large load. If you can share an instance across your publishing actors, that would be better IMO.
