### ISSUE TITLE
Once-only delivery via MessageLock: implementation?

### ISSUE THREAD

**Issue by kierenj** [justeat/JustSaying#262]
Hi - I'm just wondering how you guarantee once-only delivery here.  It looks like `IMessageLock` is the key - but I can only find a single, in-memory (and so single-process) implementation, seemingly used for tests?

**Comment by slang25** [comment]
We have an implementation we use internally that uses DynamoDB to achieve this. I'll look at what's involved in adding this as an out-of-the-box offering.

**Comment by payman81** [comment]
You can use any database that supports Optimistic Locking in your implementation of IMessageLock.

**Comment by kierenj** [comment]
That's cool - I've used a Redis key with TTL for each unique message ID this purpose before - I just wandered if an implementation was provided or left as an integration detail.  Thanks for the info!

**Comment by slang25** [comment]
@kierenj nice. Thinking about it, a dependency on dynamodb would be bloat. I think the takeaway here is that we should explain the extensibility points in the wiki and add some samples where necessary.

**Comment by HappyRainy** [comment]
AWS just announced that their SQS supports once only now. You should be able to use it as the native SQS support very soon.

**Comment by payman81** [comment]
Yeah that'll simplify things a lot.
