### ISSUE TITLE
Improve default retention period

### ISSUE THREAD

**Issue by payman81** [justeat/JustSaying#265]
Currently, the [retention period is set to 10 minutes](https://github.com/justeat/JustSaying/blob/develop/JustSaying.AwsTools/JustSayingConstants.cs#L42) after which message will disappear. This is a incredibly low value. 
A good default should be sufficiently high to ensure reasonable persistence and user can chose to have a lower retention depending on the scenario.

**Comment by stuart-lang** [comment]
AWS default is 4 days, which seems reasonable, would you agree @payman81?

**Comment by payman81** [comment]
yes 4 days is plenty

**Comment by payman81** [comment]
This issue was fixed in #272
