### ISSUE TITLE
Generic Message types are not supported

### ISSUE THREAD

**Issue by eric-davis** [justeat/JustSaying#278]
I've just started looking at JustSaying as a possible message bus solution, but have run into an issue with the handler registration system and message serialization when attempting to use generic message types. For example, I have an existing domain event class I would like to publish via JustSaying. I can't just have my event class derive from JustSaying.Models.Message since I am already deriving that event class from a base event type. And the event type has a property named Version that is of type integer that would collide with the Message class' string Version property. So, I decided to define a JustSaying message wrapper class like so:

```
public class MessageWrapper<TEvent> : Message where TEvent : IEvent
{
    public MessageWrapper(TEvent domainEvent)
    {
        this.DomainEvent = domainEvent;
    }

    public TEvent DomainEvent { get; private set; }
}
```

Then I configure the JustSaying bus like so...

```
var basicCredentials = new BasicAWSCredentials(awsAccessKeyId, awsAccessKeySecret);
CreateMeABus.DefaultClientFactory = () => new DefaultAwsClientFactory(basicCredentials);

var bus =
CreateMeABus.InRegion(awsRegion.SystemName)
    .ConfigurePublisherWith(c => c.PublishFailureReAttempts = 3)
    .WithSnsMessagePublisher<MessageWrapper<WidgetCreated>>()
    .WithSnsMessagePublisher<MessageWrapper<WidgetNameChanged>>()
    .WithSqsTopicSubscriber()
    .IntoQueue("justsaying_events")
    .WithMessageHandler<MessageWrapper<WidgetCreated>>(new WidgetCreatedHandler())
    .WithMessageHandler<MessageWrapper<WidgetNameChanged>>(new     WidgetNameChangedHandler());

bus.StartListening();
```

The issue is the way in which the message type's .Name property is serialized into the SNS message Subject and used for both the handler registration key and the serialization type. This method appears to be too simplistic to support generic message types. If I define and publish a message with a type of `MessageWrapper<WidgetCreated>`, the resulting message type's .Name value is "MessageWrapper'1". It does not include the generic parameter type. So, if I have registered handlers for multiple `MessageWrapper<>` message types, they all get incorrectly dispatched to just one of my registered message handlers...and most fail during de-serialization. The other concern with this approach is that it doesn't support non-generic types that may have the same type name, but different namespaces. Since the simplistic `Type.Name` property is being used as the key, I expect there could be collisions if you attempted to register handlers for both `MyApp.Foo.Created` and `MyApp.Bar.Created`.

**Comment by AnthonySteele** [comment]
I don't think that we should go out of our way to cater for `MyApp.Foo.Created` and `MyApp.Bar.Created`. When dealing with a distributed system it's about the contract not the implementation - there is not a guarantee or even a requirement that the software at the other end is sharing the same binary DTOs, or is even also .Net code. So name your messages unambiguously.

**Comment by eric-davis** [comment]
I see your point. My main concern was the lack of support for generic message types, but I understand your reasoning about being technology agnostic. I was just trying to avoid having to create a JustSaying-specific message wrapper for each of my existing event message classes in order to use JustSaying as a message bus. It can be done, it's just more tedious. Thanks.

**Comment by refactorthis** [comment]
I have a similar problem, but agree with above point, I still want my messages to be meaningful by themselves without generic wrappers.

I think the real underlying problem here is that you need to use the Message base class in order to use the library, would it be hard to remove this restriction?, perhaps even as a simple workaround abstracting this to an interface?

**Comment by slang25** [comment]
We have resolved this issue in the v5 beta, we now support generic message types, we'll leave it to consumers to decide if it's a good idea or not (my team uses it, and we have a need for it). Regarding the `Message` base class, we at some point want to move to a concept of message envelopes, which would enable you to drop the base class. I'd like to get a proposal out after we release v5.

**Comment by eric-davis** [comment]
Can you elaborate on this new generic message type support? Is there a code example available? I assume there is something you have to do regarding the queue/topic naming strategies to make this work?

**Comment by DEV-SHW** [comment]
@slang25 I am using JustSaying v5, with generic message types, and have run into the same scenario. Did the support for generic message types make it into the final cut for version 5?

**Comment by slang25** [comment]
@DEV-SHW Hi, yes it is in there.

[Here is the code where we can now handle generic messages](https://github.com/justeat/JustSaying/blob/master/JustSaying/Extensions/TypeExtensions.cs#L15), so it should be that generic message types no longer trip up JustSaying, however if there's still an issue then please let us know and we can look at that issue.

**Comment by duncanbrown** [comment]
I'm having some problems using generic messages. Specifically, they seem problematic when multiple generic handlers are registered against a single bus.

Here's a minimal repro:


Suppose we have a generic wrapper message type like:

```c#
public class Wrapper<T> : Message
{
    public T Foo { get; set; }
}
```

and we're going to publish/consume `Wrapper<int>` and `Wrapper<string>` messages.

We have a publisher configured like this:

```c#
var publisher = CreateMeABus
    .WithLogging(loggerFactory)
    .InRegion(RegionEndpoint.EUWest1.SystemName)
    .WithSnsMessagePublisher<Wrapper<int>>()
    .WithSnsMessagePublisher<Wrapper<string>>();
```

And - in a seprate application - handlers like this:

```c#
public class IntHandler : IHandlerAsync<Wrapper<int>>
{
    public Task<bool> Handle(Wrapper<int> message)
    {
        Console.WriteLine($"Got {message.Foo}");
        return Task.FromResult(true);
    }
}

public class StringHandler : IHandlerAsync<Wrapper<string>>
{
    public Task<bool> Handle(Wrapper<string> message)
    {
        Console.WriteLine($"Got {message.Foo}");
        return Task.FromResult(true);
    }
}
```

and configuration like this:

```c#
CreateMeABus
    .WithLogging(loggerFactory)
    .InRegion(RegionEndpoint.EUWest1.SystemName)
    .WithSqsTopicSubscriber().IntoQueue("Int").WithMessageHandler(new IntHandler())
    .WithSqsTopicSubscriber().IntoQueue("String").WithMessageHandler(new StringHandler())
    .StartListening();
```

What happens when we publish is that `Wrapper<int>` messages get handled fine, but `Wrapper<string>` messages throw deserialisation exceptions: JustSaying is trying to deserialise the `Wrapper<string>` message as a `Wrapper<int>`:


```
fail: JustSaying[0]
      Error deserialising message
Newtonsoft.Json.JsonReaderException: Could not convert string to integer: foo. Path 'Foo', line 1, position 12.
   at Newtonsoft.Json.JsonReader.ReadInt32String(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at JustSaying.Messaging.MessageSerialisation.NewtonsoftSerialiser.Deserialise(String message, Type type) in C:\projects\justsaying\JustSaying\Messaging\MessageSerialisation\NewtonsoftSerialiser.cs:line 24
   at JustSaying.Messaging.MessageSerialisation.MessageSerialisationRegister.DeserializeMessage(String body) in C:\projects\justsaying\JustSaying\Messaging\MessageSerialisation\MessageSerialisationRegister.cs:line 41
   at JustSaying.AwsTools.MessageHandling.MessageDispatcher.DispatchMessage(Message message) in C:\projects\justsaying\JustSaying\AwsTools\MessageHandling\MessageDispatcher.cs:line 49
   ```

With a bit of digging around, I think the problem is a couple of cases where information about the parameters of generic types is lost. For example:

1. The `MessageSerialisationRegister`'s keying mechanism: https://github.com/justeat/JustSaying/blob/7e478df9b69567d74a483f59d58de65bc7967ec0/JustSaying/Messaging/MessageSerialisation/MessageSerialisationRegister.cs#L13 - both `Message<int>` and `Message<string>` land up with keynames of "Wrapper`1", so only the first actually gets registered.

2. The subject of the sns notifcation set at https://github.com/justeat/JustSaying/blob/ec1d7ac2433852b5ad585bd44bdfe2293e817f72/JustSaying/AwsTools/MessageHandling/SnsTopicBase.cs#L114

**Comment by duncanbrown** [comment]
Have given a bit of thought to this.

I'd thought maybe an 'easy' fix would be to change the bits of code that currently use `Type.Name` to get a string representation of a type, to something that preserves generic parameters. But there's a problem with this - that string representation is used in the Subject of SNS/SQS messages, so changing it would break existing applications...

That being the case, I wonder if a solution would be to change the 'internal' stuff to support generics, then for the 'external' stuff - e.g. the bits that go from types to message subjects & vice-versa - allow the consumer to provide their own function, defaulting to the current non-generic method for compatibility?
