### ISSUE TITLE
Multiple Subscribers to a Specific Message from One Publisher

### ISSUE THREAD

**Issue by alexjavad** [justeat/JustSaying#284]
Hey guys.

Was really looking for some guidance on this one.

My current setup is 4 visual studio projects. 1 Publisher. 2 Subscribers. And 1 for Messages.

Subscribers are being run as windows services.

Let's say I publish 10 messages. Half of them get picked up by Subscriber1, and the other half by Subscriber2.

This is obviously not desired, as I want each message I send from the publisher to be received by BOTH Subscribers. I am not sure how to configure that to work, using the JustSaying Syntax.

I will past my code for each handler below. If anyone can provide some advice, I would greatly appreciate it.

   //Subscriber1

   public class Service
    {
        public void Start()
        {
            //create instance of bus for this endpoint
            CreateMeABus.DefaultClientFactory = () =>
                new DefaultAwsClientFactory(new BasicAWSCredentials("blahblah", "blahblah"));

            CreateMeABus.InRegion(Amazon.RegionEndpoint.USEast1.SystemName)
           .WithSqsTopicSubscriber("OrderCreate")
           .IntoQueue("MessageQueue")
           .WithMessageHandler<OrderCreate>(new OrderCreateHandler())
           .StartListening();
        }

        public void Stop()
        {

        }
    }

    public class OrderCreateHandler : IHandler<OrderCreate>
    {
        public bool Handle(OrderCreate message)
        {
            //business logic
            Console.WriteLine("RECEIVED Message: " + message);

            return true;
        }
    }

   //Subscriber2

    public class Service
    {
        public void Start()
        {
            //create instance of bus for this endpoint
            CreateMeABus.DefaultClientFactory = () =>
                new DefaultAwsClientFactory(new BasicAWSCredentials("blahblah", "blahblah"));

            CreateMeABus.InRegion(Amazon.RegionEndpoint.USEast1.SystemName)
           .WithSqsTopicSubscriber("OrderCreate")
           .IntoQueue("MessageQueue")
           .WithMessageHandler<OrderCreate>(new OrderCreateHandler())
           .StartListening();
        }

        public void Stop()
        {

        }
    }

    public class OrderCreateHandler : IHandler<OrderCreate>
    {
        public bool Handle(OrderCreate message)
        {
            //business logic
            Console.WriteLine("RECEIVED Message: " + message);

            return true;
        }
    }

In Amazon SNS, I only see one subscription. I believe that's an issue, but I also believe the JustSaying C# code should be taking care of generating the necessary plumbing in Amazon SNS/SQS for me... I just am not sure what that syntax is. 

Thanks again for helping.

**Comment by AnthonySteele** [comment]
You need to be aware of the difference between a SNS topic and an SQS queue. For this scenario, you want one SNS topic, with two SQS queues attached to it. Both queues will then receive a copy of the message.

it might be enough for you to alter your subcribers to do `.IntoQueue("MessageQueue_1")` and `.IntoQueue("MessageQueue_2")` or any other two different queue names.

**Comment by slang25** [comment]
In addition to what @AnthonySteele has said, another option is to use your own INamingStrategy (here is the default: https://github.com/justeat/JustSaying/blob/master/JustSaying/DefaultNamingStrategy.cs) then you can model the SQS queue names to fit however you need it to, for example a different queue name per project, we do a similar thing at JUST EAT. The end result will be the same, 1 topic -> 2 queues, which is what you are after.

**Comment by alexjavad** [comment]
Thank you gentlemen. This helped me a lot.
