### ISSUE TITLE
Release JustSaying 5.0

### ISSUE THREAD

**Issue by slang25** [justeat/JustSaying#292]
Tasks outstanding:
- [x] Sort out AppVeyor build
- [x] Update dependencies to latest stable
- [x] Use logging compatible with .NetStandard and .Net core
- [x] Ensure we have all the commits cherrypicked from master we want
- [x] Get a beta out : https://www.nuget.org/packages/JustSaying/5.0.0-beta-105
- [ ] Trials

Things to let slip until vNext (maybe a quicker release cycle) that we had planned to get in v5

Have I missed anything?

**Comment by AnthonySteele** [comment]
👍 Then a live trial on a non-critical component Not necessarily a .Net core one.

**Comment by stuart-lang** [comment]
Ah yes, we need a beta release first

**Comment by AnthonySteele** [comment]
Yep, a package on nuget.org with a name ending in `-beta1` will help with that.

**Comment by AnthonySteele** [comment]
On potential blocker is that [there is no released version of nlog for .net core and there won't be until after netstandard 2.0 is out](http://nlog-project.org/2016/10/30/nlog-roadmap-netcore-structural-logging.html).

We either have to wait for netstandard 2.0, or try to push the dependency on nlog out of the library.

**Comment by martincostello** [comment]
Suggest zero padding the betas. Or if we have more than 9 betas we'll get bitten by the ```10``` < ```9``` horribleness...

**Comment by slang25** [comment]
Good spot. Ok, looks like it needs doing. We're back to that discussion again. Our options I recall are:
1. [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/microsoft.extensions.logging.abstractions/)
2. LibLog
3. Our own interface, people must plug their own providers in. We could provide `JustSaying.Logging.NLog` as an optional nuget package.

I think 2 is a no-no. My preference is 1, but would also be happy with 3.

**Comment by AnthonySteele** [comment]
I don't know enough about 1 to make a decision.  😞  If you think it's good then fine, otherwise 3

**Comment by stuart-lang** [comment]
@martincostello @brainmurphy Your thoughts on logging abstractions would be welcome 🙂

**Comment by stuart-lang** [comment]
Keep switching account by accident 😄, if it isn't obvious @slang25 == @stuart-lang

**Comment by martincostello** [comment]
I'll share some code separately about what I did in my .NET Core repo for JSON fields. It's a bit hacky as the MS logging abstraction didn't allow for the custom fields.

**Comment by martincostello** [comment]
So, maybe not use the MS one (at least for now).

**Comment by stuart-lang** [comment]
@martincostello that is interesting, please do share

**Comment by AnthonySteele** [comment]
it's using `Microsoft.Extensions.Logging.Abstractions` now to solve that issue.

**Comment by dariusdamalakas** [comment]
@AnthonySteele, @stuart-lang Any updates on this? We need to upgrade AWD SDK to version 3.

Is [5.0.0-beta-313](https://www.nuget.org/packages/JustSaying/5.0.0-beta-313) being used in production by now in JustEat?

**Comment by SeanFarrow** [comment]
Hi,

Whatisthe correct way of crating a bus in v5? it no longing seems to have InRegion. Any pointers welcome please!

**Comment by stuart-lang** [comment]
@SeanFarrow If you look at [the updated README](https://github.com/justeat/JustSaying/blob/master/README.md) you will see what the new usage looks like. You now must first call `.WithLogging(...)` because logging is no longer static and is required by the other extension methods. However this might change as the open PR at the moment defers the build actions, so we could make it a little more friendly (but you're still going to need to make changes).

**Comment by jaimalchohan** [comment]
@stuart-lang how are we doing on releasing Version 5 of JustSaying?

**Comment by dariusdamalakas** [comment]
@slang25 what is the status of this? There has been very little activity lately.

**Comment by brainmurphy** [comment]
@dariusdamalakas Coincidentally, I've had a catch-up with @slang25 this morning - the plan is to complete some required work on the fluent API by end of this week. Definitely bug us if that doesn't happen!

**Comment by dariusdamalakas** [comment]
@brainmurphy cool, will do.

**Comment by dariusdamalakas** [comment]
@brainmurphy ping

**Comment by slang25** [comment]
@dariusdamalakas Hi, I have done some more work around #327, this is mostly done, and I have a few tweaks after an internal review.
I want to get this in before v5 RC as it will change the api surface. I will write up later in the PR what the change is and the reasoning behind the decisions.

**Comment by dariusdamalakas** [comment]
@slang25  +1 for getting rid of blocking calls. How is this going?

**Comment by slang25** [comment]
@dariusdamalakas In order to remove the blocking calls, we have to make the fluent api lazy, and have an awaitable build method, which you'd await to give you your publisher/subscriber.

As we were making a breaking change to the fluent api, we thought this would be an opportune time to rationalise the api. I've had a conservative effort at this, but it still leaves things "a bit weird" in the api.

Our latest efforts on this are here: #330 

It would be great to start a discussion around this API change, please give your feedback.

**Comment by 3686** [comment]
+1 for next version release please 👍

**Comment by slang25** [comment]
We've released version `5.0.0` [here](https://github.com/justeat/JustSaying/releases/tag/v5.0.0)
