### ISSUE TITLE
Usage of existing SNS and SQS resources

### ISSUE THREAD

**Issue by olifer** [justeat/JustSaying#298]
It would be really great if it could be possible to use JustSaying with existing SNS and SQS resources created preliminary (e.g. with cloud formation templates). It might be a requirement due to security or some other reasons. Currently, JustSaying overwrites policies attached to SNS/SQS. Could this behaviour be adjusted?

**Comment by dariusdamalakas** [comment]
Good point. This would also speed up JustSaying initialisation.
