### ISSUE TITLE
Failsafe events

### ISSUE THREAD

**Issue by refactorthis** [justeat/JustSaying#314]
Hi,

I currently use RabbitMQ in production however I really like the look of your library and am considering switching to managed services. A question I had though is if SNS is down I may not be able to deliver my message, in many cases this is critical as other systems must eventually be consistent and no messages can be lost.

Using other service bus technologies you can setup store-and-forward queues (MSMQ, RabbitMQ with shovel). Do you have an approach for guaranteed events to SNS if SNS is temporarily down?, what do you do at JustEat for this kind of thing?

**Comment by slang25** [comment]
Hi @refactorthis 

Great question, at Just Eat we mitigate SNS outage by using 2 regions (an active and a passive), we do this by using `.WithActiveRegion(() => ...)` and fetch a platform wide flag for the current active region, we also have a heartbeat service that tells if/when SNS is down so we can fail over. Subscribers subscribe to both regions, and don't care which is active, just cares that it gets messages.

You can read the full detail [in this blog post](http://tech.just-eat.com/2015/01/21/just-eat-and-region-failure-presenting-justsaying-v2-1/).

**Comment by refactorthis** [comment]
Excellent! Didn't realise that you had already built this functionality, that's great. Definitely gives me more confidence in this solution. 

Closing the ticket.

**Comment by refactorthis** [comment]
Actually just to add to this we have some strict requirements about what data we can send offshore, unfortunately we only have one region in Australia. Do you have plans to add encryption to the message serialisation? If not i'm happy to raise a separate issue to discuss the implementation and go from there.

**Comment by AnthonySteele** [comment]
For encryption, you should be able to supply your custom serialisation code that does whatever transform you need. Or simply have a message with a field called `string CypherText`
