### ISSUE TITLE
JustSayingFluentlyExtensions.WithMessageHandlers() Doesn't Support Single Parameter

### ISSUE THREAD

**Issue by eric-davis** [justeat/JustSaying#317]
If I invoke the `JustSayingFluentlyExtensions.WithMessageHandlers<AlphaMessage>()` method passing in an array of `IHandlerAsync<AlphaMessage>` handlers that contains more than 1 handler instance, everything seems to work as expected. But if I call that method and pass in an array of just 1 handler, I get the following exception message:

`The handler for 'AlphaMessage' messages on this queue has already been registered.`

This occurs when there are no handlers registered that could possibly cause any conflicts. I assume this is a bug?

Performing the same operation for the same handler via the `IFluentSubscription.WithMessageHandler<AlphaMessage>()` method instead works just fine.

**Comment by AnthonySteele** [comment]
Hm, that's odd.

The code for `WithMessageHandlers` actually does the samething:

```csharp
        if (handlers.Length == 1)
        {
            sub.WithMessageHandler(handlers[0]);
        }
````

So perhaps we need a test for this scenario
