### ISSUE TITLE
Blocking Async Handler Example?

### ISSUE THREAD

**Issue by eric-davis** [justeat/JustSaying#320]
Maybe I am missing something obvious here, but what is the recommended way to configure an SQS subscription to ensure that an async handler (IHandlerAsync) has time to process a message before it is pulled by another subscriber? 

My very basic async handler example looks like the following:

```
public class Handler : IHandlerAsync<Envelope>
{
    public Task<bool> Handle(Envelope envelope)
    {
        return Task.FromResult(this.Handle(envelope.Message));
    }

    private bool Handle(Message message)
    {
        // Do some stuff that may take a bit...
        return true;
    }
}
```
If I configure the queue subscription with a large `VisibilityTimeoutSeconds` value like say 60 seconds, I don't have any issues. But if I knock it down to something smaller (like 1 second) and the operation takes longer than a second, the message is delivered multiple times.

What am I missing here?

**Comment by slang25** [comment]
You are not missing anything, this is a gap IMO, I've said my thinking here: https://github.com/justeat/JustSaying/issues/291

**Comment by eric-davis** [comment]
Ok. Thanks for the reference to #291. I guess for now I'll just have to tweak the `VisibilityTimeoutSeconds` configuration to avoid this unintended concurrent duplicate message processing. Thanks.
