### ISSUE TITLE
DelaySeconds not working?

### ISSUE THREAD

**Issue by jonasbutt** [justeat/JustSaying#325]
I'm trying to use the new delay functionality of version 5.0.0. Currently I'm simply setting the DelaySeconds on the Message that gets passed to IMessagePublisher. However, messages published with a delay seem to be arriving immediately instead. 

What could I be missing?

**Comment by fgiele** [comment]
Could it be you are publishing through SNS? 
SNS doesn't support delayed messages so I suspect the subscribed queues don't get the delay either. If you publish through SNS, all messages will appear immediately on the queues and thus immediately as events to handle through JustSaying.

**Comment by jonasbutt** [comment]
Turns out I was using `WithSnsMessagePublisher` when should have been using `WithSqsMessagePublisher`.
Thanks a bunch @fgiele
