### ISSUE TITLE
QUESTION: Required AWS permissions for message publisher / subscriber?

### ISSUE THREAD

**Issue by eric-davis** [justeat/JustSaying#326]
Can anyone please point me to any documentation regarding the minimum AWS access permissions required to publish messages and subscribe to SQS queues? If not, I would suggest this info be added to the available documentation. Would be really helpful. :-)

**Comment by johnsonlu** [comment]
https://github.com/justeat/JustSaying/releases/tag/v5.0.0

> Here are the actions requred if you are both publishing and subscribing.
sns:CreateTopic,
sns:ListSubscriptionsByTopic
sns:ListTopics
sns:Subscribe
sqs:CreateQueue
sqs:DeleteMessage
sqs:GetQueueAttributes
sqs:GetQueueUrl
sqs:ListQueues
sqs:SetQueueAttributes
sqs:ReceiveMessage
If you are just publishing then you can omit the SQS actions. If you are just subscribing then you still need the SNS actions (may change in the future).
