### ISSUE TITLE
Question: how to configure JustSaying to create FIFO queues ?

### ISSUE THREAD

**Issue by aliiftikhar** [justeat/JustSaying#343]
In my application we publish few events to SNS
these events are subscribed by SQS queues.
by default justSaying creates these queues as standard queues, how can I configure it to create FIFO queues?

this is how my subscription code looks like:

CreateMeABus
    .InRegion(RegionEndpoint.EUWest1.SystemName)
    .WithAwsClientFactory(() => new DefaultAwsClientFactory(new BasicAWSCredentials(awsAccessKey, awsSecretKey)))
    .WithSqsTopicSubscriber()
    .IntoQueue("MyQueueName")
    //START Adding Subscriptions here:
    .WithMessageHandler(new OrderCreated())
    .WithMessageHandler(new OrderProcessed())
    //END Adding Subscriptions
    .StartListening();

**Comment by slang25** [comment]
At the moment we don't support this, and I think that FIFO queues have a simulation where they cannot subscribe to SNS topics, so it would only work if you were publishing straight to a queue.

**Comment by brainmurphy** [comment]
Correct; unfortunately, SNS ➡️ SQS isn't supported for FIFO queues. See here: https://aws.amazon.com/sqs/faqs/

> The following features of AWS services aren't currently compatible with FIFO queues:
> ...
> Amazon SNS Topic Subscriptions
> ...

JustSaying could _potentially_ be made to work for publishing to SQS directly (which we support). If you're interested in that @aliiftikhar, then a discussion/PR is welcome.

**Comment by PeterKneale** [comment]
> "Correct; unfortunately, SNS ➡️ SQS isn't supported for FIFO queues."
> https://aws.amazon.com/sqs/faqs/

I believe that this constraint has been removed. It no longer appears in the documentation and I just manually created a FIFO queue and was able to create a subscription to an SNS topic.

In light of this could this functionality be added?

**Comment by PeterKneale** [comment]
Sadly while it's possible to create the subscription, SNS does not actually place the message in the subscribing FIFO SQS queue so it appears this function is still not available.

https://forums.aws.amazon.com/thread.jspa?messageID=885547&#885547
