### ISSUE TITLE
QUESTION: AWS SNS/SQS Message Filtering?

### ISSUE THREAD

**Issue by eric-davis** [justeat/JustSaying#351]
Do you all have any plans to support AWS SNS/SQS Message Filtering anytime soon?

**Comment by stuart-lang** [comment]
I'd love this, and would like to open up the discussion around this.

Currently we have properties in the `Message` base class that we want to either move, or copy into message attributes (which is required for filtered subscriptions).

We'd need to balance backward compatibility with this feature, there is some overlap with the concept of "Message Envelopes" which has been discussed in other issues.

Maybe we start with a strawman implementation in a PR and work from there?

**Comment by slang25** [comment]
Just to get the ball rolling on discussion:
```csharp
  var publisher = CreateMeABus.WithLogging(loggerFactory)
                    .InRegion(RegionEndpoint.EUWest1.SystemName)
                     .WithSnsMessagePublisher<GenericMessage>(cfg => {
                    cfg.MessageAttributes = new Dictionary<string,Func<GenericMessage,string>>{
                        [nameof(GenericMessage.Tenant)] = x => x.Tenant
                    };
                });
```

```csharp
var subscriber = CreateMeABus
                .WithLogging(new LoggerFactory())
                .InRegion(primaryRegion)
                .WithFailoverRegion(secondaryRegion)
                .WithActiveRegion(() => primaryRegion)
                .WithSqsTopicSubscriber()
                .IntoQueue("queuename")
                .WithFilter(nameof(GenericMessage.Tenant), "uk") // Filter here
                .WithMessageHandler(handler);
```
