### ISSUE TITLE
.NET Framework Support

### ISSUE THREAD

**Issue by slang25** [justeat/JustSaying#382]
In the current 6.0.0 beta support for `net451` was dropped in favour of `netstandard20` which we understood to provide support for .NET 4.6.1 and up, however recently there is increasing consensus that .NET Standard 2.0 support for .NET Framework below 4.7.2 is problematic.

It might be a good idea to in this case explicitly multi-target 4.6.1, or alternatively make it clear that support below 4.7.2 will be non-ideal and possibly problematic.

Thoughts?

**Comment by martincostello** [comment]
My opinion would be to go with adding a `net461` target back.

**Comment by slang25** [comment]
Mine too, it was dropped because it felt a bit gross straddling 2 major versions of the logging abstractions package.

See here:
https://twitter.com/stuartblang/status/1034427988224421888

**Comment by AnthonySteele** [comment]
We have to support .NET framework  `4.6.x` at present for a large number of codebases, so adding it back it might be necessary.

**Comment by slang25** [comment]
We are back to this:
https://github.com/justeat/JustSaying/pull/361#issuecomment-399457168

😐

**Comment by martincostello** [comment]
I guess fixing this is a must for 6.0.0 now?

**Comment by AnthonySteele** [comment]
I think so, yes. We need a second target, be it `4.6.2` or `4.5.1`

**Comment by martincostello** [comment]
I thing based on it being a major bump since 5 and 4.5.1 being out of support (?) now, we should go with `net462`.
