### ISSUE TITLE
JustSaying 6 Change notes (WIP)

### ISSUE THREAD

**Issue by adammorr** [justeat/JustSaying#389]
Not so much of an issue but more of a dumping ground for information related to the hopefully upcoming JustSaying 6 release...

- Now requires `sns:SetSubscriptionAttributes` IAM action to support https://github.com/justeat/JustSaying/pull/367 and https://github.com/justeat/JustSaying/pull/387

**Comment by slang25** [comment]
Added a mention to it [here](https://github.com/justeat/JustSaying/releases/tag/untagged-d8abb8fb3f837f055c6b), we might want to make it more obviously when the release notes get finalized so that it doesn't get missed.
