### ISSUE TITLE
Use code analysers

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustSaying#401]
As an important library, JustSaying should have high code standards.

we can use [code analysers like is done here](https://github.com/justeat/JustEat.StatsD/pull/126) to enforce standards.

My experience with adding those analysers is that it's intensive work for a day or so while all the issues are worked through, and then is almost invisible. I have confirmed that there are > 100 such analyser warnings in JustSaying. This is not an unusual number.

Most common issue are in my experience around:

* `await`  without `ConfigureAwait(false)`
* string operations without a specified culture
* methods that can be static
* public fields that should not be mutable
* correct `Exception` declarations
* correct implementation of `IDisposable`, and flagging classes that own disposable resources but are not `IDisposable` in turn.

**Comment by AnthonySteele** [comment]
A goof way to do it is [like this, by linking in a ruleset](https://github.com/NuKeeperDotNet/NuKeeper/blob/master/NuKeeper/NuKeeper.csproj#L10). The repo can contain multiple rulesets, for different goals. e.g. [This ruleset for tests allows underscores in method names](https://github.com/NuKeeperDotNet/NuKeeper/blob/master/CodeAnalysisRulesForTests.ruleset), whereas the shipping code does not.

**Comment by martincostello** [comment]
You can also use the `NoWarn` property like this: 

https://github.com/justeat/httpclient-interception/blob/fa872e0b7d36d3ec7e53c5ab49e7fa26d90edd4b/tests/HttpClientInterception.Tests/JustEat.HttpClientInterception.Tests.csproj#L4

I prefer that approach personally, as you can have a default `ruleset` file in `Directory.Build.props` and just ignore things that you don't want in specific projects.
