### ISSUE TITLE
Review compared to "Open-source library guidance"

### ISSUE THREAD

**Issue by martincostello** [justeat/JustSaying#402]
Before we release version `7.0.0`, we should review the codebase with respect to the new [_"Open-source library guidance"_](https://docs.microsoft.com/en-gb/dotnet/standard/library-guidance/) documentation from Microsoft and determine what, if anything, we _should_ do for JustSaying while we have the opportunity to make breaking changes.

The only obvious thing to consider that we don't currently do is [strong-naming](https://docs.microsoft.com/en-gb/dotnet/standard/library-guidance/strong-naming), which would allow the library to be consumed by applications/libraries that are/need strong-naming themselves.

Similar changes elsewhere on the same theme include:
  * justeat/JustEat.StatsD#147
  * justeat/httpclient-interception#56

**Comment by AnthonySteele** [comment]
I'm sure that we will _debate_ strong naming.

**Comment by AnthonySteele** [comment]
We have agreed to allow strong naming.

**Comment by martincostello** [comment]
I'll look at doing a PR like the other two, unless someone else has a burning desire to do it.

**Comment by slang25** [comment]
On strong-naming, JustBehave is now signed, but structuremap isn't and it looks like there is no intention from them to do it, not sure the best way forwards with this 😕

**Comment by martincostello** [comment]
This _might_ fit in with what I'm doing in #431, where I'm trying to make the DI more pluggable as a whole.

If that all works, we could replace StructureMap with something else that is, like the Microsoft one?

**Comment by martincostello** [comment]
Re-reviewing this, it looks like the path forward is to move the tests for StructureMap into their own test assembly that doesn't need `[assembly: InternalsVisibleTo("...")]` and by necessity not strong-name `JustSaying.Extensions.DependencyInjection.StructureMap`. Then everything else should be sign-able and we can turn it on for the rest of the assemblies.
