### ISSUE TITLE
Improve Listen() implementation in SqsNotificationListener

### ISSUE THREAD

**Issue by adammorr** [justeat/JustSaying#404]
See what we can do to improve [this logic](https://github.com/justeat/JustSaying/blob/master/JustSaying/AwsTools/MessageHandling/SqsNotificationListener.cs#L89) based on the information in [David Fowlers](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md) async guide

**Comment by AnthonySteele** [comment]
Specific patterns:

* The `ContinueWith` on line 104 is against the guidance.
* the ` using (var linkedCts` on line 216 appears to be correct, as the `CancellationTokenSource` is disposed after use.
* Launching threads happens via the `IMessageProcessingStrategy` on line 259. This might or might not be good.

**Comment by slang25** [comment]
I'm currently having a play about some more with `IAsyncEnumerable` (blog post almost finished), which I'm also experimenting with putting in your spike, and exposing it optionally on the side. I'm not suggesting going down that route for JustSaying, but could become part of a nice composable toolkit that plays nicely with JustSaying.

**Comment by slang25** [comment]
The concerns [listed here](https://github.com/justeat/JustSaying/issues/404#issuecomment-432999342) have been addressed by these :tada: :
https://github.com/justeat/JustSaying/pull/440/commits/77dba4bbc91c63cf4d424b6da3b455357f6f74fe
https://github.com/justeat/JustSaying/pull/403
https://github.com/justeat/JustSaying/pull/453
https://github.com/justeat/JustSaying/pull/440/commits/d2ed621e564c0dcfbfb65681f1aeb7efb23df066
