### ISSUE TITLE
Task creation review for Listen

### ISSUE THREAD

**Issue by slang25** [justeat/JustSaying#421]
There's been much discussion over these lines of code:

https://github.com/justeat/JustSaying/blob/a3115052bf2c6db43fe82c48cf60b0043fc0d8c9/JustSaying/AwsTools/MessageHandling/SqsNotificationListener.cs#L96-L105

I wanted to start the discussion by outlining what I think are issues, and non issues with the current implementation:

- [`StartNew` is odd](https://blog.stephencleary.com/2013/08/startnew-is-dangerous.html). Knowing this, I actually think it is correct here. We start the immediate synchronous part of the `ListenLoop` on a thread-pool thread, and we implicitly chose the default task scheduler not the current, this is actually what we want IMO.
- `ContinueWith` should be avoided, according with recent guidance. For me, in this particular usage, this is more of an aesthetics thing. `ContinueWith` could be rewritten using `async`/`await`, and I think we should do this.
- While neither of the above are problems in themselves, there is a problem with the combination of them, the `Task` returned from `StartNew` only represents the immediate synchronous part of the loop, which finishes immediately, causing the logging in the `ContinueWith` to run immediately too. This needs addressing. **Update** No 🤦, I was missing the `Unwrap` part, this is all working as expected.

The ListenLoop is using the threadpool responsibly and isn't doing long blocking, so we don't need to mark the task as `LongRunning`. The synchronous start of the loop is extremely short, so it doesn't need to necessarily begin on a separate threadpool thread, but it is currently so we should stick with that IMO.

Option 1:
```csharp
_cts = new CancellationTokenSource();

// Explicit fire-and-forget
_ = Task.Run(async () =>
    {
        bool isFaulted;
        try
        {
            while (!_cts.IsCancellationRequested)
            {
                await ListenLoop(_cts.Token).ConfigureAwait(false);
            }
        }
        catch (Exception ex)
        {
            // Change AggregateExceptionDetails to take a regular exception
            log.LogWarning($"[Faulted] Stopped Listening - {queueInfo}\n{AggregateExceptionDetails(ex)}");
            isFaulted = true;
        }
        finally
        {
            if (!isFaulted) // Could also check _cts.IsCancellationRequested and get rid of this.
            {
                log.LogInformation($"[Cancelled] Stopped Listening - {queueInfo}");
            }
        }
    });
```

There are some other variations of this, I'll follow up with in the comments.

**Comment by AnthonySteele** [comment]
Agreed that `ContinueWith(t => LogTaskEndState(` is ludicrous. it should be something like:

```
  while (!_cts.IsCancellationRequested)
  {
        await ListenLoop(_cts.Token).ConfigureAwait(false);
    }
LogTaskEndState(t, queueInfo, _log);
```

**Comment by slang25** [comment]
Yeah, currently it's also logging the exception, and if it was cancelled or not, but I'm not sure if that's going to be doubling up logging from elsewhere. I guess it can't of been critical cause it's never worked.

**Comment by AnthonySteele** [comment]
[As per these comments](https://github.com/justeat/JustSaying/pull/403#discussion_r231192784), I do want a message logged when the listener shuts down, in order to determine if a worker shut down gracefully or not. But yes, at present it seems that we have several of those.

**Comment by slang25** [comment]
I've been testing this code against a simplified example, and I see now that I forgot the `Unwrap` method 🤦, the `ContinueWith` is actually working fine cause it is hanging off the Task inside of the async delegate. So it's only cancellation that would be an issue, not the end state logging.

Which is good news, cause it means this code we have today behaves as we want it to, it just reads a bit weird.

**Comment by slang25** [comment]
Concerns have been resolved by:
https://github.com/justeat/JustSaying/pull/403
https://github.com/justeat/JustSaying/pull/453
https://github.com/justeat/JustSaying/pull/440/commits/d2ed621e564c0dcfbfb65681f1aeb7efb23df066
