### ISSUE TITLE
Remove IMessageLock

### ISSUE THREAD

**Issue by martincostello** [justeat/JustSaying#458]
In JustSaying we have two interfaces, `IMessageLock` and `IMessageLockAsync`.

We provide an implementation of `IMessageLockAsync` which just delegates to an inner `IMessageLock`, but we don't provide a built-in implementation of `IMessageLock` at all.

To simplify things as everything's async now anyway, we should just provide `IMessageLockAsync` (and drop the `Async` suffix?), and leave any "it's not really async" implementation to anyone who wants to use the interface as JustSaying consumes it all in an async way anyway.

**Comment by slang25** [comment]
Just to give a little background here, `IMessageLock` was the existing interface, and a commonly used implementation exists inside JustEats codebase (could be open sources) that uses dynamodb.
`IMessageLockAsync` was added specifically to support the async nature of the dynamodb calls, and  `BlockingMessageLock` was added as a backward compatibility shim.

**Comment by AnthonySteele** [comment]
Ayep. it might be time to remove the deprecated sync version.

**Comment by martincostello** [comment]
See #461.
