### ISSUE TITLE
Pass SNS RequestId to IMessageMonitor

### ISSUE THREAD

**Issue by maurofranchi** [justeat/JustSaying#462]
Is it possible to pass the ```requestId``` returned by the SNS publish API to the ```IMessageMonitor``` methods so we can log it?
This would help AWS investigating on open issues with SNS as they normally ask for the SNS requestIds (and time-stamp).

**Comment by martincostello** [comment]
This sounds like something we could consider for the v7 release to improve the "debuggability" of on-going usage of JustSaying to do SQS/SNS (rather than of JustSaying itself).

**Comment by slang25** [comment]
I know @JosephWoodward had the same requirement a while ago. It would be ideal to solve this in the aws-sdk client, we could probably do something with the recent change they made to allow us to pass in our own `HttpHandlers`/`HttpClient`. It would also be handy if we could enable the logging in the sdk to allow this (see here: https://github.com/aws/aws-sdk-net/pull/915).

**Comment by martincostello** [comment]
I recently updated some internal stuff that adds to `IHttpClientFactory` to propagate `X-Amzn-Trace-Id` in HTTP requests and also to add it to our Serilog context where available.

Are there similar request headers for SNS/SQS (and Dynamo) that I could similarly pick-up and pass on where available to make things a bit nicer while we wait for something first-class that's baked in?

**Comment by AnthonySteele** [comment]
A comment: We are currently working with `PublishAsync` and changing the signature of it.
`PublishAsync` can publish to SNS or SQS via the same interface and abstracts the differences, which AWS does not.

But `PublishAsync` still returns `void` - so it could be further modified to return some data about the publish?

**Comment by AnthonySteele** [comment]
[`MessageResponse` is Justsaying's dto](https://github.com/justeat/JustSaying/blob/master/JustSaying/AwsTools/MessageHandling/MessageResponse.cs)

**Comment by slang25** [comment]
💩

**Comment by AnthonySteele** [comment]
`MessageResponse` only has 2 fields,  but on the plus side we can extend it. Or even return it from `PublishAsync`.

**Comment by AnthonySteele** [comment]
Should be fixed for v7.0 in #463 

Can close this issue?

**Comment by maurofranchi** [comment]
Thank you for your help!

**Comment by martincostello** [comment]
Fixed by #463.
