### ISSUE TITLE
SqsBasicConfiguration.RetryCountBeforeSendingToErrorQueue Naming Might be Misleading

### ISSUE THREAD

**Issue by AmoraskPangea** [justeat/JustSaying#467]
Currently, I'm trying to configure a JustSaying Message Bus that does not attempt a re-delivery to my message handlers before sending a failed message to the error queue. I don't want to opt out of the error queue entirely. Quite the contrary; I prefer that my messages go directly to the error queue rather than being retried against our message handlers. 

To accomplish this, I've zeroed in on a few configurations, but the one that seems most appropriate is the `RetryCountBeforeSendingToErrorQueue` property of the `SqsBasicConfiguration` model. I'm opening this issue as more of a question because, as far as my testing has gone, the `RetryCountBeforeSendingToErrorQueue` property actually **includes the initial delivery of the message to the message handler** and I was wondering if this was the desired behavior? 

For instance, if I have a message bus subscription configured like so:
```csharp
CreateMeABus
    .WithLogging(_loggerFactory)
    .InRegion(_regionEndpoint)
    .WithNamingStrategy(() => _namingStrategyFactory.GetNamingStrategy())
    .WithSqsTopicSubscriber()
    .IntoDefaultQueue()
    .ConfigureSubscriptionWith(configuration => configuration.RetryCountBeforeSendingToErrorQueue = 0)
    .WithMessageHandler(handler);
```
The expected behavior is that the initial message will be delivered, but there will be no subsequent retries before delivering the message to the error queue. Instead, JustSaying will actually bubble up a SQS exception that the `maxReceiveCount` cannot be 0; basically the `RedrivePolicy` is invalid.

If I use the same configuration, but set `RetryCountBeforeSendingToErrorQueue` to 1, the message is successfully delivered once. Set it to two and the message is successfully delivered twice.

I've figured out how to achieve what I'm looking for by setting `RetryCountBeforeSendingToErrorQueue` to 1, but I just wanted to point out that it seems incorrect to count the initial delivery of a message to a message handler as a "Retry". 

Love this product and thanks in advance for your help!

**Comment by AnthonySteele** [comment]
Not stale. related to #506
