### ISSUE TITLE
Remove/deprecate CreateMeABus and JustSayingFluently*

### ISSUE THREAD

**Issue by martincostello** [justeat/JustSaying#471]
Now that #431 has been merged which provides the basis for a new _"builder API"_ for using JustSaying, which should start work on slowly deprecating the existing [`CreatMeABus`](https://github.com/justeat/JustSaying/blob/master/JustSaying/CreateMeABus.cs) class in `master` so that by the time we release `7.0.0` it no longer exists, as well as removing the existing `JustSayingFluently*` classes.

**Comment by martincostello** [comment]
Unless there are compelling reasons not to do so, the new API should have feature parity with the `6.x.x` releases in the new API surface.

Feature parity in this sense means that you can achieve a comparable result, but it does not necessarily need to be like-for-like in terms of it being a default behaviour or not, naming or location in the API.

**Comment by gkinsman** [comment]
@martincostello for V7, can we perhaps scope this issue to removing CreateMeABus while leaving JustSayingFluently? The new fluent API depends on it so we'd need to pass those calls straight through to the JustSayingBus if we wanted to rip out fluently too. 

JustSayingStack bypasses it completely so we don't need to think about it much. We could also just make JustSayingFluently internal to hide it?

**Comment by martincostello** [comment]
The original idea was to implement it on top of the old one just to get the new API in, and then after that hoist the implementation up (or move it) so that CMAB and JSF could be deleted.

If we want to not wait to do that for v7, I'd be happy to settle for making all of it internal so that it's effectively removed and then can be chipped-away at separately.

**Comment by gkinsman** [comment]
That sounds fair - I'm tempted to spike out removing it in the case that it is just a matter of passing the calls through to JSB, but I suspect it might be a little trickier than that. If that fails I'll make it internal 👍
