### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by martincostello** [justeat/JustSaying#472]
As part of the introduction of the new builder API (see #471), the README documentation, samples etc. need to be updated to use the new API.

**Comment by PeterKneale** [comment]
# More diagrams
I'd like to see some diagrams that explain how the various options present in the bus configuration map to different architectures. Ideally these might be described using a few different 'patterns'.
ie:

## Configuration Pattern Pub/Sub
- `publisher` configuration
```cs
                config.Publications(x =>
                {
                    x.WithTopic<X>();
                });
```
- `subscriber1` configuration
```cs
                config.Subscriptions(x =>
                {
                   x.ForTopic<X>();
                });
```
- `subscriber2` configuration
```cs
                config.Subscriptions(x =>
                {
                   x.ForTopic<X>();
                });
```
## Resulting architecture
![image](https://user-images.githubusercontent.com/710594/54751323-b3c8d200-4c2e-11e9-8951-e186bc685593.png)

# Producing the diagrams
- [PlantUML sequence diagrams](http://plantuml.com/sequence-diagram) seem to lend themselves to this kind of documentation.
- They are plain text and the markup is easily learnt just through experimentation 
- They are [linkable](https://www.planttext.com/?text=dLJBRXen5DtxAsw6DMfnqYvGgK8I5AbgAv0ZTT5MoCpS31R6jlnemz_NysGc7HfI5YFikUTnpq5SEy-j3ti9gTuRhL1vGhpm4c4PDYni83YXSlWKd6VyK7pbAeFvDmRiAtl3LeniHORmgBNVw2VYTa8PRlaURdYwowqEAhlLKbiOBHQBcxlRxeH-Ml8iApZfsyxzCZeIgJ1S-Svx4kaXYQQaSDjuzqFDZP4YvLvebS18YdphSui70l5ZZXnGOz22jbbyJWZ65Ggt9MNS9SArvIh7lx19lIayQ2FI1BWhJkldbFG4SCLW5J0WZ2OLTiNMCLINMh51EwdHbo-YwG2QrkYh_ZhDmFE8IWl_I2avCbTYxN7T-7nthXBzNwLcf_Uj4fdDu5Wwp6Qa-54PCErToTyMClu-khU8wkV7Na_JPWBsw1pF4Rm-zbfIzEOZJMxv8RBq6vl27KhnArhiyZH5dSr3p-2nw8DLe7T55bKEMifU2Aub15EzgnpqFNze8XbtEvt2P-5y8--wabzgIzKHixACrqZIGKdwQibYwNcwK_gtn2m_jJhlJWm6C1vC02ukeEm1FJQcJgpwaWGTbg2d9QxZC_xjaZy0)
- There is a website that renders the below to an image: https://www.planttext.com/
- There is a [visual studio code plugin](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml) that can render them using a plantuml server 
- There is a docker image for the server
```sh
 docker run -d -p 8080:8080 plantuml/plantuml-server:jetty
```

## PlantUML used to produce the above

```plantuml
@startuml component

title PubSub using JustSaying and AWS SNS/SQS
hide footbox
skinparam BackgroundColor #EEEBDC
skinparam BoxPadding 20
skinparam ParticipantPadding 20

box "Publishing\nApplication" #lightgrey
    participant Publisher order 1
end box
box "AWS" #orange
    participant "AWS SNS Topic" as SNS_Publisher order 2
    participant "AWS SQS Queue #1" as SQS_Subscriber1 order 3
    participant "AWS SQS Queue #2" as SQS_Subscriber2 order 4
end box
box "Subscribing\nApplication #1" #lightgrey
    participant "Subscriber" as Subscriber_1 order 5
end box
box "Subscribing\nApplication #2" #lightgrey
    participant "Subscriber" as Subscriber_2 order 6
end box

== Publishing ==
group publishing
    Publisher-[#Green]>SNS_Publisher: Publish message to SNS Topic
    SNS_Publisher-[#gray]>SQS_Subscriber1: Deliver message to SQS Queue
    SNS_Publisher-[#gray]>SQS_Subscriber2: Deliver message to SQS Queue
    return ok
end

== Polling ==
group subscriber polling
    SQS_Subscriber1<[#Green]-Subscriber_1: List messages
    return Message returned
end 
group subscriber polling
    SQS_Subscriber2<[#Green]-Subscriber_2: List messages
    return Message returned
end 

== Acknowledging ==
group subscriber acknowledging
    SQS_Subscriber1<-[#Green]-Subscriber_1 !! : Delete message
end 
group subscriber acknowledging
    SQS_Subscriber2<-[#Green]-Subscriber_2 !! : Delete message
end 
@enduml
```
