### ISSUE TITLE
Investigate DI compatibility

### ISSUE THREAD

**Issue by martincostello** [justeat/JustSaying#473]
As part of the new builder API, we should investigate how this would plug into various Dependency Injection frameworks so that the core library is agnostic and provides some simple shims (such as [`IServiceResolver`](https://github.com/justeat/JustSaying/blob/master/JustSaying/Fluent/IServiceResolver.cs)) to bridge common implementations with JustSaying to make consumption easy.

Examples include, but are not limited to:
  * ~~Microsoft's .NET Core DI (#474)~~ ✔️ 
  * Autofac
  * Ninject
  * ~~StructureMap (#482)~~ ✔️ 

I'd imagine the obvious ones to include in the first instance are containers we use internally at Just Eat.

For those we consider worth implementing for others' use, we can provide "extension" NuGet packages that install alongside JustSaying that provide the glue between it and a given DI framework "out-of-the-box".

**Comment by iancooper** [comment]
I suggest we look at a DI-Friendly Framework approach: http://blog.ploeh.dk/2014/05/19/di-friendly-framework/

I'll create a branch that works this way

**Comment by martincostello** [comment]
After discussion yesterday with @brainmurphy and @iancooper, it was decided that Microsoft and StructureMap providers built-in is enough for v7 to ship as that solves most of internal consumption.

Any other providers can be contributed by the community if neccessary.
