### ISSUE TITLE
Sample application

### ISSUE THREAD

**Issue by martincostello** [justeat/JustSaying#476]
In order to make consumption-by-example easier, and also provide a more realistic test-bed for implemenation, we should consider adding a sample application to the repo that illustrates configuration and usage of JustSaying to send and receive messages.

I'm thinking of something like [this example](https://github.com/justeat/httpclient-interception/tree/master/samples) application I made for [JustEat.HttpClientInterception](https://www.nuget.org/packages/JustEat.HttpClientInterception/), which also has tests of itself, which provides a simple way to consume the library in-situ without having to publish it via NuGet, as well as providing a second level of integration test as part of CI.

**Comment by slang25** [comment]
It would be great to have a sample publisher from aspnetcore, and a subscriber in a console app using the `IHostedService`, showing how to hook it up to `ServiceProvider`, deal with the cancellation tokens etc, and a pair that show it configured for in traditional .NET Framework projects.

**Comment by martincostello** [comment]
I like that idea 👌

**Comment by PeterKneale** [comment]
If I were to take a look at doing this would something like the below suffice:
- an aspnet core 2.1 web api application  
    - publishing events in from within a controller
    - subscribing to events from within a hosted service (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1)
- a console application 
    - subscribing to events and displaying them on a console
- a docker-compose arrangement that demonstrates
   - acceptance tests using `pafortin/goaws` as a replacement for the AWS

disclaimer: I'm using JustSaying at work and would like to use this as a testbed to collect feedback about anything I may be misunderstanding or misconfiguring.

**Comment by slang25** [comment]
That would be fantastic, having samples created from someone with a fresh pair of eyes is great, it will highlight confusing any confusing APIs and missing docs 😃

**Comment by martincostello** [comment]
Hi @PeterKneale - yes that all sounds reasonable. I'd go with 2.2 rather than 2.1 so we're current, then later in the year we could update the sample to 3.0.

Personally I'd err away from having a common library, and try and keep the applications a bit more "sample-y" by not making it to production-y so it's easy for software developers of all abilities to follow, rather than going down too much of a "here's a perfectly engineered" solution. For example, I'd publish directly from the controller, rather than implementing a service layer and abstractions etc.

Another thing I was considering was making the sample be a very simple "online food ordering" system, so it fitted in with the Just Eat branding 😃

**Comment by PeterKneale** [comment]
One thing about the documentation that doesn't appear to be clear is around the dependency injection.

- I ask because `CreateMeABus....` appears in the readme and uses a fluent builder pattern but the responsibilities of the interfaces is a bit hard to descern.
    - ie: `IAmJustSayingFluently : IMessagePublisher` 
- `JustSaying.Extensions.DependencyInjection.Microsoft` appears in the source but is unpublished and uses the newer service collection extension approach.

**Comment by martincostello** [comment]
@PeterKneale We're in the middle of migrating from `CreateMeABus` to the new Fluent API. The new API currently wraps the old one, once we've got the tests in a better shape (which is nearer to done that not), then we'll start gutting the implementation out of CreateMeABus so we can deleted it.

Ideally the sample would use the new API directly - it would be a good way to help validate its design. Apologies for the lack of documentation on the new API at this point, I didn't want to expend a lot of time on the docs at the time the PR was originally merged on the basis the design might change further and didn't implement all the features yet.

**Comment by PeterKneale** [comment]
The new API definitely feels more consistent with the dotnet core experience but I'm having trouble getting it working - probably because I've done something wrong below. I'm not sure of the relationship between the `BackgroundService` and the `_bus.Start(...)` call.
The SNS topic, SQS queue and subscription are created in AWS but the below results in an infinite loop

*output*
```
JustSaying:Information: Created topic 'orderreceivedevent' on ARN 'arn:aws:sns:ap-southeast-2:783838941924:orderreceivedevent'.
JustSaying:Information: Created SQS topic subscription on topic 'orderreceivedevent' and queue 'orderreceivedevent'.
JustSaying:Information: Checking if queue 'orderreceivedevent' exists.
JustSaying:Information: Checking if queue 'orderreceivedevent_error' exists.
JustSaying:Information: Created topic 'orderreceivedevent' on ARN 'arn:aws:sns:ap-southeast-2:783838941924:orderreceivedevent'.
JustSaying:Information: Created SQS topic subscription on topic 'orderreceivedevent' and queue 'orderreceivedevent'.
JustSaying:Information: Checking if queue 'orderreceivedevent' exists.
JustSaying:Information: Checking if queue 'orderreceivedevent_error' exists.
JustSaying:Information: Created topic 'orderreceivedevent' on ARN 'arn:aws:sns:ap-southeast-2:783838941924:orderreceivedevent'.
JustSaying:Information: Created SQS topic subscription on topic 'orderreceivedevent' and queue 'orderreceivedevent'.
JustSaying:Information: Checking if queue 'orderreceivedevent' exists.
JustSaying:Information: Checking if queue 'orderreceivedevent_error' exists.
```


*code*
```cs
using Amazon;
using JustSaying.Messaging.MessageHandling;
using JustSaying.Models;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace JustSaying.Samples.ConsoleSubscriber
{
    internal class Program
    {
        private static async Task Main()
        {
            var host = new HostBuilder()
                .ConfigureLogging((hostContext, logging) =>
                {
                    logging.AddConsole();
                    logging.AddDebug();
                })
               .ConfigureServices((hostContext, services) =>
               {
                   services.AddJustSaying(config =>
                   {
                       config.Client(x =>
                       {
                           x.WithBasicCredentials("xxxxxxxxx", "xxxxxxxxxxx");
                       });
                       config.Messaging(x =>
                       {
                           x.WithRegion(RegionEndpoint.APSoutheast2);
                       });
                       config.Subscriptions(s =>
                       {
                           s.ForTopic<OrderReceivedEvent>();
                       });
                   });
                   services.AddJustSayingHandler<OrderReceivedEvent, OrderReceivedHandler>();
                   services.AddHostedService<Subscriber>();
               })
               .UseConsoleLifetime()
               .Build();

            using (host)
            {
                await host.StartAsync().ConfigureAwait(false);

                Console.WriteLine("Started. Press <enter> to stop.");
                Console.ReadLine();

                await host.StopAsync().ConfigureAwait(false);
            }
        }
    }

    public class OrderReceivedEvent : Message
    {
        public OrderReceivedEvent(string customer)
        {
            Customer = customer;
        }

        public string Customer { get; private set; }
    }

    public class OrderReceivedHandler : IHandlerAsync<OrderReceivedEvent>
    {
        private readonly IMessagingBus _bus;
        private readonly ILogger<OrderReceivedHandler> _log;

        public OrderReceivedHandler(IMessagingBus bus, ILogger<OrderReceivedHandler> log)
        {
            _bus = bus;
            _log = log;
        }

        public Task<bool> Handle(OrderReceivedEvent message)
        {
            _log.LogInformation("Handling OrderReceivedEvent");

            return Task.FromResult(true);
        }
    }

    public class Subscriber : BackgroundService
    {
        private readonly IMessagingBus _bus;
        private readonly ILogger<Subscriber> _log;

        public Subscriber(IMessagingBus bus, ILogger<Subscriber> log)
        {
            _bus = bus;
            _log = log;
        }

        protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _log.LogInformation("Subscriber executing");

            _bus.Start(stoppingToken);

            return Task.CompletedTask;
        }
    }
}
```

**Comment by martincostello** [comment]
This is now underway as part of #527.

**Comment by martincostello** [comment]
#527 has now been merged, which makes a huge contribution to this. Will leave the issue open for now as we may iterate on it further before we ship v7.0.0.

**Comment by martincostello** [comment]
General consensus yesterday is that the new sample is "good enough", as it were, it ship with v7. Any other bells and whistles can be added post-release.

**Comment by martincostello** [comment]
Treating this as done.
