### ISSUE TITLE
WithMessageHandler overload not helpful

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustSaying#484]
Having both of these overloads to register a handler makes some proposed new features harder:

```csharp
        WithMessageHandler<T>(IHandlerAsync<T> handler) where T : Message;

        WithMessageHandler<T>(IHandlerResolver handlerResolver) where T : Message;
```

The first can't be used with any system that passes transient data to the handler instance constructor.

A new handler instance each time seems safer in general, otherwise it requires handler authors coding for re-entrancy, and all dependencies being long-lived, which is all not obvious.

**Describe the solution you'd like**

Remove the overload that takes a `handler` instance. 
It is used in tests, but a dummy `IHandlerResolver` that only returns a supplied instance could be used instead there.

**Additional context**

Considered as useful for some kind of message context accessor injected into handler constructor.

**Comment by martincostello** [comment]
Yeah, this is an artifact of the design we want to move away from. The new API internally just uses the variant that uses the resolver.

https://github.com/justeat/JustSaying/blob/ef0e4a6b16cdef4388a948650866e79c351da48a/JustSaying/Fluent/TopicSubscriptionBuilder%601.cs#L104

This should get tidied up as part of #471.
