### ISSUE TITLE
Update test timeout logic for integration tests?

### ISSUE THREAD

**Issue by martincostello** [justeat/JustSaying#497]
I just stumbled across this while looking at the open PRs against AspNetCore:

https://github.com/aspnet/Extensions/blob/master/src/TestingUtils/Microsoft.AspNetCore.Testing/src/TaskExtensions.cs

Thoughts on using a similar approach rather than this?

https://github.com/justeat/JustSaying/blob/e79209608893e273256ff3630f09d0e1b02b5a40/JustSaying.IntegrationTests/Fluent/IntegrationTestBase.cs#L98

**Comment by slang25** [comment]
Just spotted this nice addition this morning: https://github.com/aspnet/Extensions/pull/903/files#diff-f9fc84e9e08124073588f47f8858a507R20

**Comment by AnthonySteele** [comment]
Looks OK, and our tests will verify if it's doing what we need.

**Comment by martincostello** [comment]
@slang25 Yeah, that's how I found it 😄
