### ISSUE TITLE
Support for async / await pattern

### ISSUE THREAD

**Issue by ILikePies** [justeat/JustSaying#50]
...so that i/o bound handlers become more resource-efficient.

Had a preliminary chat with @payman81 and decided to go for something along the lines of adding `IAsyncHandler<T>` interface, similarly to `IHandler<T>`.

This way, the change will be non-breaking and it will be up to users to pick whether they want to go async in a particular scenario.

**Comment by dariusdamalakas** [comment]
@ILikePies  - did you ever had time to work on this?

**Comment by ILikePies** [comment]
@dariusdamalakas - I attempted to do that around Feb but failed as this would require substantial refactoring. I reckon things have improved since then but haven't had a look yet.

**Comment by dariusdamalakas** [comment]
Thats what I thought too - if that hasn't been done from the ground up, than adding async is not that trivial. Thanks

**Comment by AnthonySteele** [comment]
I second this. I have seen code that implements IHandler, and then needs to do http requests while processing the message, so (ab)uses the `HttpClient` class by calling `.Result()` immediately on returned tasks. Ack.

A rule of thumb is that if you need to re-synchronise (.e.g. when using async/await in a commandline app)  then you should do it once as high up as possible. Supplying an `IAsyncHandler` interface would push these waits up into the JustSaying Framework, even if the handling of them wasn't great.

**Comment by AnthonySteele** [comment]
General comments on a way to approach this here: https://gist.github.com/AnthonySteele/44804be39f19a871b0a6

**Comment by dariusdamalakas** [comment]
@AnthonySteele , good stuff. This is also roughly in the direction that we have discussed this with @payman81 and @brainmurphy . I.e. follow B) without the sync support internally, and this will be a major version bump.

**Comment by AnthonySteele** [comment]
@dariusdamalakas Thanks. I agree that it should be a major version bump.

The take-away from that gist (aside from the basics of `async ... await` ) is that if you code to prefer async handlers, then it only takes a dozen or so lines of code to also support existing sync handlers. This would allow existing code to be upgraded and still compile and run. But then you might need to mark the sync version as deprecated in order to encourage going async.

**Comment by payman81** [comment]
@AnthonySteele thanks for that thourough analysis. I agree with your conclusion that solution B is preferable given how easy it is to support existing handlers. 
After all, Messaging is inherently asynchronous.

**Comment by AnthonySteele** [comment]
This PR: https://github.com/justeat/JustSaying/pull/203 is for this issue.

**Comment by AnthonySteele** [comment]
Fixed in 4.0
