### ISSUE TITLE
Consider randomizing queues and topics initialization order

### ISSUE THREAD

**Issue by dv00d00** [justeat/JustSaying#514]
This feature request is related to the production incident we had recently. We have a feature which works in international environment, currently it works with 6 countries, each country defines its own JustSaying stack. We were doing this initialization in parallel. This caused issues when we were recycling instances in the morning. AWS was responding with `403 RateLimitExceeded` to JustSaying calls which are checking existence of queue and it metadata.

We was able to consistently reproduce this in our staging environment.

How to reproduce:
1. Spawn 6 fresh ec2 instances with the worker.
2. Initialize a 6 JustSaying stacks in parallel in the same order in all of those boxes.
3. Each JustSaying stack will initialize queues in the same order for every country.
4. AWS will start to respond with 403

I got a confirmation from AWS support that rate limiting is happening in SQS on a per **queue** basis.

**Describe the solution you'd like**

Introduce randomization for the order of queue/topic setup during the JustSaying publisher / listener setup.

**Describe alternatives you've considered**

Introduce exponential backoff and retries for 403 requests from AWS APIs.

**Additional context**
We have removed parallel stacks initialization.
We have also added a randomized order in which countries are being initialized.
There is still a chance of this occurring in the single country environment when the burst of activations will occur: imagine a case when 12 instances added at once, all of them will do initialization in the same order, which potentially can cause issues.

**Comment by AnthonySteele** [comment]
What are the downsides of a backoff and retry strategy - purely that it will take longer?

**Comment by AnthonySteele** [comment]
> that rate limiting is happening in SQS on a per **queue** basis.

Do parallel stacks share queues, or do they use a different set of queues for each stack? I thought that they did not overlap.

Is it every new instance that is querying each queue once; or is each new instance querying each queue once for each parallel stack?

If it's the first case then it's simply due to starting very many new instances at once, and a backoff and retry should allow some instances to start quickly?

If it's the second case of multiple calls to the same queue per instance, then a result could be cached in-memory to avoid duplicate calls.

**Comment by dv00d00** [comment]
> Do parallel stacks share queues, or do they use a different set of queues for each stack? I thought that they did not overlap.

No, all queues were unique to each stack, but the order of stacks was shared between all instances

> Is it every new instance that is querying each queue once; or is each new instance querying each queue once for each parallel stack?

Every instance checks status of every queue and topic, the feature is publishing and listens to messages in every country

> If it's the first case then it's simply due to starting very many new instances at once, and a backoff and retry should allow some instances to start quickly?

Potentially retry/backoff would fix the issue in any case

More background
This was happening in the account which historically would consume and generate much less sqs/sns traffic than another one we have, there should be some internal account level setting which AWS support can manipulate to limit the amnt of concurrent calls to sqs api

The randomization of init order is a neat effect, but I believe it also introduces delayed setup, now there a lot of network effect going on during the init phase, which does not expose any Task<T> and looks like pure builder calls. 

If we choose to go the api calls resiliency route, there might still be value in delaying init phase up to actual startup call. Current builder signature hides its async nature by callin .GetAwaiter().GetResult()

**Comment by martincostello** [comment]
The "lazy" stuff will _hopefully_ be improved by the builder-pattern redesign for v7, though I imagine there's other things can be improved further in there once we get further along with the internal refactoring and deprecation of the current API that's for-now wrapped by the new builders.
