### ISSUE TITLE
A channels based IMessageProcessingStrategy

### ISSUE THREAD

**Issue by slang25** [justeat/JustSaying#529]
I've been playing with `Channels` and it seems like a natural fit for JustSaying.
I've put together a simple implementation (with no tests at the moment so it's early days), which IMO has a more intuitive behaviour than the current implementation.

See here: https://github.com/slang25/JustSaying.ChannelsProcessing/blob/master/JustSaying.ChannelsProcessing/ChannelsMessageProcessingStrategy.cs

What this implementation also does is eagerly gets the next batch of messages, which is good and bad, so the config values would need to be tuned carefully (see the [xml doc comments here](https://github.com/slang25/JustSaying.ChannelsProcessing/blob/master/JustSaying.ChannelsProcessing/ChannelsMessageProcessingStrategy.cs#L21-L40)).

It seems like a good candidate to be something that comes out-of-the-box.

**Comment by martincostello** [comment]
Maybe this is something we can look at adding into a post v7 release?
