### ISSUE TITLE
Queue Creation and subscription on startup rather than at first request?

### ISSUE THREAD

**Issue by JamesPrescott** [justeat/JustSaying#530]
**Is your feature request related to a problem? Please describe.**

We came across an issue recently within one of our projects where the first request received after the startup of the box would be significantly slower than any other requests, but only when messaging was involved in the request.

We found that most of the response time was taken up by queue creation and subscription, even to messages that weren't involved in that request. After that, all is well 😄we've tried looking at our implementation to see if there's any way to avoid this, but from looking at other implementations, we found that we weren't doing it too differently from anyone else.

**Describe the solution you'd like**

It would be cool if we could try to invoke this initialisation process sooner, rather than at the point of first request if possible.

**Describe alternatives you've considered**

There might also be the possibility of only dealing with necessary queues at the above point rather than all at once? From looking at the common implementation I understand this might be a longer-term change.

**Additional context**

**Comment by slang25** [comment]
When you say first request, are you talking about publishing? There is a library within Just Eat that wraps JustSaying, this library defers some work until the first published message, it may be this you are seeing rather than a behaviour of JustSaying.

**Comment by AnthonySteele** [comment]
@slang25 yes, this the first SNS/SQS publish, in an API that receives a http request, and publishes a message about it.
