### ISSUE TITLE
Add ability to disable the message handlers from config file

### ISSUE THREAD

**Issue by maurofranchi** [justeat/JustSaying#531]
**Is your feature request related to a problem? Please describe.**
This is not a problem on JustSaying, but sometimes in production when something happens (ie: the app that is running on it can't connect to an external service or the CPU goes up) to the server where the application that uses justsaying runs, we have to terminate the machine in order to mitigate the issue that it is causing and to avoid that the messages are still handled (removing the machine from the load balancer won't avoid this). Unfortunately this prevents us from investigate on the issue any further as we can't collect the dump of the memory as we had to terminate the server.

**Describe the solution you'd like**
What I am requesting is to have a way in the application config file to tell JustSaying to stop handling a particular message (or all of them). 
This can also be used as a feature/handle toggle for normal roll-out.

**Describe alternatives you've considered**
Implement it manually on the single applications that use JustSaying. 

**Additional context**
n/a.

**Comment by martincostello** [comment]
I think this is more of a design consideration to make easy to signal that _something_ should be able to easily tell message processing to stop and then start again later (I’m thinking something similar to .NET config’s change tokens).

“Config file” doesn’t really work outside .NET Framework, and is also usually a static  read-once file, so you wouldn’t be able to change its value once it started up.
