### ISSUE TITLE
Silent Deletion of Message w/ Unrecognized Format from Queue

### ISSUE THREAD

**Issue by JarrodJ83** [justeat/JustSaying#534]
**Describe the bug**
If there is a message in a queue being consume by JustSaying that it cannot serialize it silently deletes the message from the queue. Even after turning on tracing you just see a "Didn't handle message <MessageBody>. No serialiser setup" with no indication that it is deleting the message from the queue. Only after digging through the source was I able to figure out what was happening after hours of scratching my head. I was actually playing with SNS Subscription Filter Policies at the time which made this even more allusive as the first impression I got was that the messages were never making it to my queue in the first place.

**Steps To reproduce**
Publish a message to a queue that is being consume by JustSaying that wasn't a part of the JustSaying configuration.

**Expected behaviour**
Message would be skipped and the redrive policy of the queue would eventually take over. Since the default settings are to use dead letter queues I would have expected this to retry until it ended up there.

**Actual behaviour**
Message is silently deleted from queue.

**System information:**
v6.0.1

**Comment by brainmurphy** [comment]
This is long-standing behaviour in here: https://github.com/justeat/JustSaying/blob/master/JustSaying/AwsTools/MessageHandling/MessageDispatcher.cs

```csharp
            try
            {
                typedMessage = _serializationRegister.DeserializeMessage(message.Body);
            }
            catch (MessageFormatNotSupportedException ex)
            {
                _logger.LogTrace("Could not handle message with Id '{MessageId}' because a deserializer for the content is not configured. Message body: '{MessageBody}'.",
                    message.MessageId, message.Body);
                await DeleteMessageFromQueue(message.ReceiptHandle).ConfigureAwait(false);
                _onError(ex, message);
                return;
            }
```

Agree - this is dumb.

**Comment by timrog1** [comment]
+1 for changing this behaviour. Just lost a few hours to this.

**Comment by martincostello** [comment]
Maybe we can add something in for v7 in the options somewhere that specifies was the message dispatcher should do with such messages (throw vs. delete)?

**Comment by JarrodJ83** [comment]
@martincostello Maybe I am missing something but why would the framework ever manually "delete" a message rather than just let the SQS Redrive Policy handle this? My thought would be to just log the exception and remove `await DeleteMessageFromQueue(message.ReceiptHandle).ConfigureAwait(false);` and let SQS handle the rest.
