### ISSUE TITLE
Callback/delegate on subscriber message sent to dead letter queue

### ISSUE THREAD

**Issue by Tyf0x** [justeat/JustSaying#541]
Hi,
we are trying to perform some actions only when a message is sent to the dead letter queue (when all retries have failed).

We haven't found any way of doing this with the current implementation.

We very much would like to have a delegate exposed through the `ConfigureSubscriptionWith` (similar to the `OnError` delegate) that would only be actioned when a message fails to be processed.

**Comment by adammorr** [comment]
Hello!

Have you looked at the backoff strategy capabilities? That can be used to perform additional actions if a message fails to be handled and can be configured per queue.

It will execute for each failure but the approximate receive count of a message is exposed so you could use that as a gauge of whether a message is destined for the DLQ. You just need to be conscious of visibility timeouts of a queue before doing too much processing within your implementation.

Hope this helps

Adam

**Comment by Tyf0x** [comment]
Hi, thanks for the suggestion!

I'll look more into the  `IMessageBackoffStrategy`.
