### ISSUE TITLE
Support for SNS SSE (Server-side Encryption)

### ISSUE THREAD

**Issue by martalexandra** [justeat/JustSaying#551]
I need support for server-side encryption in SNS, so I'd like to add it.
I've been working on it, and should have a PR  to submit soon.

**Comment by martincostello** [comment]
Is this similar to #363?

**Comment by martalexandra** [comment]
#363 Added support for server-side encryption in the SQS queues, I need it in the SNS topic as well.
I'm using a similar approach to #363 to add this when creating a topic.

**Comment by martalexandra** [comment]
PR #553 submitted

**Comment by martincostello** [comment]
Resolved by #575.
