### ISSUE TITLE
EventHandler try to regist a server got error

### ISSUE THREAD

**Issue by jovi-Li** [justeat/JustSaying#557]
in the demo ,I try to regist a service on OrderReadyEventHandler ,but get error . the code like this ：
    public OrderReadyEventHandler(
            ILogger<OrderReadyEventHandler> log
            , ITestService test
            )
        {
            _log = log;
            _test = test;
        }
and  I had add the this testserver to the service collection. code in startup：
 services.AddScoped<ITestService, TestService>();

error info:

  | Name | Value | Type
-- | -- | -- | --
▶ | $exception | {System.InvalidOperationException: Cannot resolve 'System.Collections.Generic.IEnumerable`1[JustSaying.Messaging.MessageHandling.IHandlerAsync`1[JustSaying.Sample.Restaurant.Models.OrderReadyEvent]]' from root provider because it requires scoped service 'JustSaying.Sample.Restaurant.OrderingApi.ITestService'.    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)    at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)    at JustSaying.ServiceProviderResolver.ResolveHandler[T](HandlerResolutionContext context) in D:\2019\Codes\JustSaying\JustSaying.Extensions.DependencyInjection.Microsoft\ServiceProviderResolver.cs:line 49    at JustSaying.JustSayingFluently.WithMessageHandler[T](IHandlerResolver handlerResolver) in D:\2019\Codes\JustSaying\JustSaying\JustSayingFluently.cs:line 284    at JustSaying.Fluent.TopicSubscriptionBuilder`1.JustSaying.Fluent.ISubscriptionBuilder<T>.Configure(JustSayingFluently bus, IHandlerResolver resolver) in D:\2019\Codes\JustSaying\JustSaying\Fluent\TopicSubscriptionBuilder`1.cs:line 110    at JustSaying.Fluent.SubscriptionsBuilder.Configure(JustSayingFluently bus) in D:\2019\Codes\JustSaying\JustSaying\Fluent\SubscriptionsBuilder.cs:line 168    at JustSaying.MessagingBusBuilder.BuildSubscribers() in D:\2019\Codes\JustSaying\JustSaying\MessagingBusBuilder.cs:line 272    at Microsoft.Extensions.DependencyInjection.IServiceCollectionExtensions.<>c.<AddJustSaying>b__3_9(IServiceProvider serviceProvider) in D:\2019\Codes\JustSaying\JustSaying.Extensions.DependencyInjection.Microsoft\IServiceCollectionExtensions.cs:line 173    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)} | System.InvalidOperationException

**Comment by martincostello** [comment]
You need to use `ILogger<OrderReadyEventHandler>` - the Microsoft DI system does not register `ILogger` (the non-generic) with the service container.

**Comment by jovi-Li** [comment]
thanks .  I copy the wrong code  ,actually it is 
  public OrderReadyEventHandler(
            ILogger<OrderReadyEventHandler> log
            , ITestService test
            )
        {
            _log = log;
            _test = test;
        }

the exception is cause by  ITestSercice

**Comment by martincostello** [comment]
That's still just `ILogger` though.

**Comment by jovi-Li** [comment]
thanks .  I copy the wrong code  ,actually it is 
  public OrderReadyEventHandler(
            ILogger  <  OrderReadyEventHandler  >   log
            , ITestService test
            )
        {
            _log = log;
            _test = test;
        }

the exception is cause by  ITestSercice

**Comment by martincostello** [comment]
Change the registration to `services.AddTransient<ITestService, TestService>()` - you can't use scoped services without having a scope (created by [`serviceProvider.CreateScope()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderserviceextensions.createscope?view=aspnetcore-2.2)).

That's usually done for you in response to HTTP requests to your application by request middleware,/MVC., but JustSaying handlers don't operate within such a scope as the message loop runs in the background. You need to either use transient or singleton dependencies for your handlers.

**Comment by jovi-Li** [comment]
got it,  thanks .
