### ISSUE TITLE
sample application with intoqueue[question]

### ISSUE THREAD

**Issue by bshowket** [justeat/JustSaying#560]
How can i subscribe to multiple queue in the example JustSaying.Sample.Restaurant.OrderingApi?

what i am looking for is to add 

```
.IntoQueue("CustomerOrders1")
                    .ConfigureSubscriptionWith(c => { c.MessageRetentionSeconds = 60; })
                        .WithMessageHandler<OrderAccepted>(new NotifyCustomerOfAcceptedOrder())
                    .ConfigureSubscriptionWith(c => { c.MessageRetentionSeconds = 300; c.VisibilityTimeoutSeconds = 60; })
                        .WithMessageHandler<OrderFailed>(new NotifyCustomerOfFailedOrder())


.IntoQueue("CustomerOrders2")
                    .ConfigureSubscriptionWith(c => { c.MessageRetentionSeconds = 60; })
                        .WithMessageHandler<OrderAccepted>(new NotifyCustomerOfAcceptedOrder())
                    .ConfigureSubscriptionWith(c => { c.MessageRetentionSeconds = 300; c.VisibilityTimeoutSeconds = 60; })
                        .WithMessageHandler<OrderFailed>(new NotifyCustomerOfFailedOrder())

.IntoQueue("CustomerOrdersN")
                    .ConfigureSubscriptionWith(c => { c.MessageRetentionSeconds = 60; })
                        .WithMessageHandler<OrderAccepted>(new NotifyCustomerOfAcceptedOrder())
                    .ConfigureSubscriptionWith(c => { c.MessageRetentionSeconds = 300; c.VisibilityTimeoutSeconds = 60; })
                        .WithMessageHandler<OrderFailed>(new NotifyCustomerOfFailedOrder())
```

thanks in advance

**Comment by martincostello** [comment]
The sample application is written against the new fluent API that's coming in v7. To subscribe to multiple queues in that API, you'd do something like this [here](https://github.com/justeat/JustSaying/blob/a898a7f17f490fbb51ec788bc7a3167b21adaf74/samples/src/JustSaying.Sample.Restaurant.KitchenConsole/Program.cs#L54-L62):

```csharp
config.Subscriptions(x =>
{
    for (int i = 1; i < 10; i++)
    {
        x.ForQueue<OrderPlacedEvent>((builder) =>
        {
            builder.WithName($"CustomerOrders{i}")
                   .WithReadConfiguration((subscription) =>
                   {
                       subscription.MessageRetention = TimeSpan.FromMinutes(1);
                   });
        });
    }
});
```

Code aside, what's the overall goal you're trying to achieve? It _looks_ like you want N queues with all the same types of messages in them all listened to simultaneously in the same app?

**Comment by bshowket** [comment]
Yes , this is correct. I want each queue will have their own url same type of message, where each IOT device will be listening for new message using long polling on to their own queue url. 

I am not sure if their is any batter way to accomplish this. Thanks for your help!

**Comment by martincostello** [comment]
OK, so that's not how you'll want to configure things, assuming I've understood correctly.

With the code as written above, each IoT device would be trying to listen for messages on each queue, which wouldn't scale and would lead to thread starvation and/or delays in processing messaging.

Instead you'd want each IoT device to listen to one queue/topic with the name being configurable based on what the specific device needs to listen to.

**Comment by bshowket** [comment]
Thanks, that's sounds like how it should be done. So you are suggesting one queue and topics for each customerorders?

If it's not too much trouble, can I ask you to show me a small example based on v7 example program? Really appreciate your help on this one.
