### ISSUE TITLE
Support SQS Tag on Create

### ISSUE THREAD

**Issue by slang25** [justeat/JustSaying#569]
It could be worth thinking about how this functionality could work in JustSaying:
https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-sqs-now-supports-tag-on-create/

**Comment by martincostello** [comment]
That would be cool to add, though might be a push to cram into 7 given how far behind that is.

If we add it, I think it should be opt-in, would need some way to allow arbitrary numbers and names of tags etc. to be applied (via a config registration callback to modify an `IDictionary<string, string>` like `Action<IDictionary<string, string>> configureTags` with some sensible minimal defaults?) and I guess it would need some extra default IAM permissions.
