### ISSUE TITLE
Restore test coverage to previous levels

### ISSUE THREAD

**Issue by martincostello** [justeat/JustSaying#579]
As part of refactoring the tests and removing JustBehave etc. the test coverage has taken a hit. Before shipping 7.0.0, we need to get the coverage back to a decent level with integration tests using the pattern we reach consensus on being "desired".

As part of this, some _specific_ tests have been deleted. The test cases removed are documented below.

  * `WithSqsTopicSubscriber.WhenSubscribingToTopicInAnotherAccount.ICanReceiveMessagePublishedToTopicInAnotherAccount`
  * `WithSqsTopicSubscriber.WhenOneBusIsSubscribedToTwoRegions.MessagesPublishedToBothRegionsWillBeReceived`
 * `WithSqsTopicSubscriber.WhenAFailoverRegionIsSetup.MessagesArePublishedToTheActiveRegion`
  * `WithSqsPointToPointSubscriber.WhenOneBusIsSubscribedToTwoRegions.MessagesPublishedToBothRegionsWillBeReceived`
  * `WithSqsPointToPointSubscriber.WhenAFailoverRegionIsSetup.MessagesArePublishedToTheActiveRegion`

~Some other tests are flaky and have been marked with `[AwsFact(Skip = "Test is flaky")]`~ Resolved by #580

**Comment by gkinsman** [comment]
I think we can probably close this, as coverage is now up to ~81% or so in master?
