### ISSUE TITLE
I would like to be able to stat out the time-on-queue for messages

### ISSUE THREAD

**Issue by petemounce** [justeat/JustSaying#60]
I would like to be able to know how long a message has spent on a queue before being successfully processed - so the difference between `publish time` and `successfully-processed time`.

I would like that stat to be possible to publish to my monitoring, so I can alert when the time-on-queue is too high.

**Comment by payman81** [comment]
There are a number of ways to do this. 
* having an envelope for messages that contains metadata around the message including publish time, receive count etc...
* Use a co-relation id to work out time difference between messages

But none of these have been implemented yet.

Alternatively, you can watch your incoming queue for number of messages and use that as your main metric to track inefficiencies in your handlers. This is available right now and no change is required to the library.

**Comment by petemounce** [comment]
It would be very useful to add an `IDictionary<string,string>` to `JustSaying.Models.Message` for things like correlation IDs and metadata - that would give it the same extensibility model as http headers.

**Comment by payman81** [comment]
That's similar to envelope feature. 
In the first version, I would add it to Message base with caution. Last thing you want is adding to message payload for things that most people won't care.

**Comment by dariusdamalakas** [comment]
Actually, this is what we ended doing - we've adead Headers to the messages in form of `IDictionary<string,string>`, proved to be really useful.
