### ISSUE TITLE
Where is `AddJustSaying()` in nuget?

### ISSUE THREAD

**Issue by donaldgray** [justeat/JustSaying#673]
Really like the look of this lib but can't find `AddJustSaying()` extension method anywhere in the published nuget package - I see it's been 8months since a release so is it just a case that it's not in there yet? If so, do you have an ETA of when it will be released?

**Comment by martincostello** [comment]
Hi - It's part of the future v7 release, which includes a rewrite of the configuration API for the library.

Unfortunately we don't have a date we can commit to for its release at this time.

**Comment by donaldgray** [comment]
Ok, no probs, thanks for the quick response.

I'm just starting a rewrite so can use the current config API for now. When using the current config - how can I use something like localstack or goaws for local testing? Is the simplest way to implement my own `IAwsClientFactory` and set that as DefaultClientFactory?  E.g.

```csharp
CreateMeABus.DefaultClientFactory = () => new MyAwsClientFactory(awsOpts.Credentials, isLocal);
```

**Comment by martincostello** [comment]
Yep, that should be the way to override it.

**Comment by donaldgray** [comment]
Nice - thank you.

I'll keep an eye for the new release and close this for now. 👍
