### ISSUE TITLE
Message abstract class

### ISSUE THREAD

**Issue by mrxrsd** [justeat/JustSaying#679]
Hi,

In the readme looks like you are intending to remove the need of inheritance of message abstract class. Are you doing this in the new version? 

Thank you for all your awesome work in this tool.

**Comment by martincostello** [comment]
I'm not sure why "(currently)" is in the README, but my understanding is that there's no active work to remove this happening at the moment. If it does change it's probably not going to be until after version 7 (which we don't have a concrete date to ship at this time).
