### ISSUE TITLE
Unable to find "AddJustSaying"

### ISSUE THREAD

**Issue by lsappidibluenumber** [justeat/JustSaying#684]
**Describe the bug**
I am unable to find "AddJustSaying" even including the JustSaying packages.

**Comment by martincostello** [comment]
`AddJustSaying()` is in the code in master for the v7 release, which has not yet shipped.

**Comment by lsappidibluenumber** [comment]
May I know when it is published?

**Comment by martincostello** [comment]
We don't currently have a planned date to ship v7.

If you subscribe to releases for the repository you'll receive a notification when we do ship it:

![image](https://user-images.githubusercontent.com/1439341/80857284-f2f68e80-8c48-11ea-96d1-7c791caa0f66.png)

**Comment by lsappidibluenumber** [comment]
Thank you very much for response.
