### ISSUE TITLE
How to create Multiple handlers for the same message

### ISSUE THREAD

**Issue by lsappidibluenumber** [justeat/JustSaying#688]
**Describe the bug**
_I have multiple projects with the same handlers, How can I create a message with multiple handlers to catch that message?._

**Comment by maurofranchi** [comment]
Hello @lsappidibluenumber maybe it is not clear to me but if I have understood well you want to make sure that all the handlers for messagr X you have in all of your projects will be able to handle a copy of the same message. Is that right? 

In that case you just need to set justsaying up to register your handler to the topic where that message is published to. Make sure the queue that is created in each project is different from the other ones otherwise you will end up having 2 or more projects listening to the same queue and processing only the messages that are not processed by the other projects. 
You can find an example here https://github.com/justeat/JustSaying/blob/master/README.md#2-register-a-subscription

**Comment by lsappidibluenumber** [comment]
Hello @maurofranchi thanks for the response, my question is what you have guessed, but I am using in the same way for multiple handlers in different projects.  Can this distribute the message copy to all the handlers?

**Comment by maurofranchi** [comment]
@lsappidibluenumber you get a copy of the message only if every project listens to a different queue subscribed to the same topic to which the message is published.
So basically project A has to listen to `myMessage-queue-A` queue, project B to `myMessage-queue-B` and so on, for `myMessage` published to topic `myMessage-topic`. 

Can you please share a snippet of the code where you register your handlers in every project and the one for the publisher (if you publish the message)?

**Comment by lsappidibluenumber** [comment]
Publisher:
![image](https://user-images.githubusercontent.com/62096735/81664845-8dcb4600-945d-11ea-9c0b-492f6e3b6346.png)


Project-A: Subscriber
![image](https://user-images.githubusercontent.com/62096735/81664904-a176ac80-945d-11ea-9d70-c73f6207662d.png)


Project-B: Subscriber
![image](https://user-images.githubusercontent.com/62096735/81665091-e4d11b00-945d-11ea-81be-e4abb2f61471.png)


**Also I am getting each message twice to the handler**

**Comment by maurofranchi** [comment]
@lsappidibluenumber you are publishing the messages twice, once to a queue and once to the SNS topic. Just use the SNS topic configuration  and remove the SQS one https://github.com/justeat/JustSaying/blob/master/README.md#2a-configuring-publishing-options

**Comment by maurofranchi** [comment]
Also make sure you use 2 different `awsOptions.BlueNumbersCreationQueue`and `awsOptionsBlueNumbersUpdationQueue` values for project A and project B otherwise they would listen to the same queue.

**Comment by lsappidibluenumber** [comment]
@martincostello thanks for the response.  I am using the SQS to store the message, and also I want use `awsOptions.BlueNumbersCreationQueueand awsOptionsBlueNumbersUpdationQueue` in both the projects A and B.

**Comment by maurofranchi** [comment]
> I am using the SQS to store the message

I would advise against using a queue to store the messages as a message has a retention time after which AWS deletes it from the queue. Maybe you can store the JSON in a DynamoDB table when you handle it?

Also you are not using a different queue name than the one you are using in the projects that handle the messages so you are basically deleting the message once it is handled (justsaying does that for you). 

> I want use `awsOptions.BlueNumbersCreationQueueand awsOptionsBlueNumbersUpdationQueue` in both the projects A and B.

As I said before, you use the same queue in multiple projects, a message will be handled by only one project only (rarely by 2 as AWS SQS guarantees at least 1 delivery of the message). The other projects won't know anything about the message. On the other hand, if you just subscribe multiple queues to the same topic and use them in the 2 projects (prj A with queues A1, A2, project B with queues B1, B2), all of them will receive a copy of the message.

**Comment by lsappidibluenumber** [comment]
Hello all,

thanks for your response.  I have resolved this issue.
