### ISSUE TITLE
InstancePosition is still lurking about in JustSaying

### ISSUE THREAD

**Issue by antonjefcoate** [justeat/JustSaying#7]

**Comment by dariusdamalakas** [comment]
What is InstancePosition? Is that something internal to JustEast ?

**Comment by justeattech** [comment]
That's correct - It was added before the library was open source.


*Payman Labbaf Senior Developer*
*------------------------------*JUST EAT Group - Fleet Place House, 2 Fleet
Place, London EC4M 7RF, UK
*WEB* www.just-eat.com*MOB* +44 (0) 788 618 5759*SKYPE* payman_labbaf
*------------------------------*
Payman forgets his tag but manages to sneak past John #minifistpump

On 6 June 2015 at 22:48, Darius Damalakas <notifications@github.com> wrote:

> What is InstancePosition? Is that something internal to JustEast ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/justeat/JustSaying/issues/7#issuecomment-109653197>.
>

-- 

------------------------------
This is an e-mail from the company JUST EAT plc. This e-mail may contain 
confidential information and/or privileged or personal advice. This e-mail 
is intended for the addressee(s) stated above only. If you receive this 
e-mail by mistake, please return it to JUST EAT plc without producing, 
distributing or retaining copies hereof. Thank you.

**Comment by dariusdamalakas** [comment]
Thanks. I was also interesting in the reasoning behind having JustSaying.Models assembly. I thought base Message class could live well in JustSaying.Messaging assembly under JustSaying.Messaging namespace. Any reason for having Message defined in a separate assembly?
