### ISSUE TITLE
Enable subscribing directly to SNS topics without having an associated SQS queue

### ISSUE THREAD

**Issue by shaynevanasperen** [justeat/JustSaying#726]
**Is your feature request related to a problem? Please describe.**
No problem. Just seems like a gap in the feature set.

**Describe the solution you'd like**
To be able to subscribe directly to an SNS topic using the same fluent syntax, and implementing the same `IHandlerAsync<T>` interface.

**Describe alternatives you've considered**
None.

**Additional context**
It should be possible for an application to receive push notifications which are time-sensitive in nature. Applications may want to receive real-time notifications that are useless to know about if they are delivered later. So if an application is offline when the notification is pushed, it doesn't want to get that notification delivered later when it is online again.

**Comment by gkinsman** [comment]
I think this is solvable by setting a low queue TTL instead of an alternative receive mechanism, and AWS don't currently provide a more suitable delivery mechanism than SQS. Feel free to re-open this if you have any other suggestions on how this might be possible!
