### ISSUE TITLE
provide custom implementation of IPublishEndpointProvider 

### ISSUE THREAD

**Issue by dariusdamalakasintelliflo** [justeat/JustSaying#75]
Hi,

What is the best way to provide a different IPublishEndpointProvider implementation when registering publishers and subscribing to topics?    

Can't find how to do that, all I can see is that JustSayingFluently.cs:70 calls CreatePublisherEndpointProvider(..) which creates news a new instance. 

Ultimately i want to configure topic name, i.e. have it configurable based on a number of environment params, not only just message type.

**Comment by payman81** [comment]
You can achieve this in a few steps.

First you need to extend MessagingConfig with your additional configuration values.
````c#
public interface IExtendedMessagingConfig : IMessagingConfig
{
	string Environment { get; set; }
}
public class ExtendedMessagingConfig : MessagingConfig, IExtendedMessagingConfig
{
	public string Environment { get; set; }
}
````

Then, you can extend IPublishEndpointProvider with your implementation. This class will generate topic names for you.
````c#
public class ExtendedPublishEndpointProvider : IPublishEndpointProvider
{
	private readonly IExtendedMessagingConfig _config;
	private readonly string _topicName;

	public ExtendedPublishEndpointProvider(IExtendedMessagingConfig config, string topicName)
	{
		_config = config;
		_topicName = topicName;
	}

	public string GetLocationName()
	{
		return string.Format("{0}_{1}", _config.Environment, _topicName);
	}
}
````

Now you can extend JustSayingFluently and override the method that returns your implementation of IPublishEndpointProvider. 
````c#
public class ExtendedJustSayingFluently : JustSaying.JustSayingFluently
{
	protected internal ExtendedJustSayingFluently(IAmJustSaying bus, IVerifyAmazonQueues queueCreator) : base(bus, queueCreator)
	{
	}

	public override IPublishEndpointProvider CreatePublisherEndpointProvider(SqsReadConfiguration subscriptionConfig)
	{
		return new ExtendedPublishEndpointProvider((IExtendedMessagingConfig)Bus.Config, subscriptionConfig.Topic);
	}
}
````

Finally, you should change the fluent syntax to use your extended versions of above types. This step is optional but helps move some boring plumbings away behind the fluent syntax. 
````c#
public static class CreateMeABus
{
	public static IMayWantOptionalSettings InRegionWithCustomSettings(string region, IExtendedMessagingConfig config)
	{
		config.Regions.Add(region);

		config.Validate();

		var messageSerialisationRegister = new MessageSerialisationRegister();
		var justSayingBus = new JustSayingBus(config, messageSerialisationRegister);

		var amazonQueueCreator = new AmazonQueueCreator();
		var bus = new ExtendedJustSayingFluently(justSayingBus, amazonQueueCreator);

		bus
			.WithMonitoring(new NullOpMessageMonitor())
			.WithSerialisationFactory(new NewtonsoftSerialisationFactory());

		return bus;
	}
}
````

I hope this helps.

**Comment by dariusdamalakasintelliflo** [comment]
Thanks, will have a look at this tomorrow (today am stuffed with other todos). Will update once i've tried this out.

**Comment by payman81** [comment]
Great. It would be good to know how you get on.

**Comment by dariusdamalakasintelliflo** [comment]
Hm, seems SqsReadConfiguration.Topic is insternal, so can't really access that.

**Comment by payman81** [comment]
You can change the topic name that is generated using the code In my earlier comment. Isn't that enough for your scenario?

**Comment by dariusdamalakasintelliflo** [comment]
Sorry, wasn't clear enough. In your code above in ExtendedJustSayingFluently class we override CreatePublisherEndpointProvider so that we could supply our own implementation. This is all fine, but I also need to read subscriptionConfig.Topic. This is the base topic name that I later can modify in custom ExtendedPublishEndpointProvider  implementation. However, that property is internal.  This code works fine if it sits in the JustSaying assembly.

**Comment by payman81** [comment]
Right - No need for Topic property to be internal. 
Can you send me a PR?

**Comment by dariusdamalakasintelliflo** [comment]
Sure, will do. thanks.

**Comment by payman81** [comment]
I'll close this issue - PR for this will be welcome.

**Comment by dariusdamalakas** [comment]
Thanks. The issue #79 and the WithNamigStrategy config options solves as nicely, so it's no longer necessary to expose this. Happy with closing this.
