### ISSUE TITLE
Provide a message transformer for message publishing

### ISSUE THREAD

**Issue by ghost** [justeat/JustSaying#76]
Hi,

Is there a way to inject a message mutator for publisher? Interested for Sns publisher only for the moment.
  I.e. we want to add extra stuff to the message before publishing. Such as timestamp, authentication token, user context, etc, or anything else that can be extracted to a separate message mutator. 

I see there's only serialization happening in SnsTopicBase.Publish(Message), is there an extension point I could use to modify the message just before publishing?

Thanks

**Comment by dariusdamalakasintelliflo** [comment]
P.s. maybe there is a way to do this, just could figure out how, or missed it.

**Comment by payman81** [comment]
Currently, message mutators are not available. I'll label this issue as enhancements.

**Comment by dariusdamalakasintelliflo** [comment]
We'll need to work-around this then in the meantime.  thanks for response.
