### ISSUE TITLE
Allow to configure message body format that JustSaying expects

### ISSUE THREAD

**Issue by dariusdamalakas** [justeat/JustSaying#80]
Hi,

Currently JustSaying posts messages which are in this format

```
{ 
     Subject = <messageType>,
     Message = <messageBody>
}
```

This works well when using JustSaying to send and receive messages. However, this is also a limitation because there are cases when we are not in control of the incoming message format. 

One example is using [SES](http://aws.amazon.com/ses/) to send emails. This service also allows to listen for delivery notifications, such as [bounce notifications](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notifications.html). In this case, SES publishes notifications to our topic of choice. When JustSaying polls for new messages, the received message looks completely different:

``` javascript
{
  "Type" : "Notification",
  "MessageId" : "--id--",
  "TopicArn" : "arn:aws:sns:eu-west-1:963735208092:--topicname--",
  "Message" : "{\"notificationType\":\"Bounce\",\"bounce\":{\"bounceSubType\":\"General\",\"bounceType\":\"Permanent\",\"reportingMTA\":\"dsn; a6-180.smtp-out.eu-west-1.amazonses.com\",\"bouncedRecipients\":[{\"emailAddress\":\"bounce@simulator.amazonses.com\",\"status\":\"5.1.1\",\"diagnosticCode\":\"smtp; 550 5.1.1 user unknown\",\"action\":\"failed\"}],\"timestamp\":\"2015-06-05T13:48:57.172Z\",\"feedbackId\":\"0000014dc3fb5186-78d7691e-7665-47f9-8f81-182e8da28ba1-000000\"},\"mail\":{\"timestamp\":\"2015-06-05T13:48:55.000Z\",\"source\":\"--sourceemail--\",\"messageId\":\"0000014dc3fb4cac-23402d11-bfe7-4735-b663-5b6eca2f0daf-000000\",\"destination\":[\"bounce@simulator.amazonses.com\",\"--dest-email--\"]}}",  
  "Timestamp" : "2015-06-05T13:48:57.223Z",
  "SignatureVersion" : "1",
  "Signature" : "--..",
  "SigningCertURL" : "--..--",
  "UnsubscribeURL" : "--..--"
}

```

What we'd like to do is to be able to add custom serializators, which would be able to parse this message. IMessageSerialisationFactory is already acting in that area, but what will need to be changed is how the message type is discovered (currently that is built-in), and where the message body is being loaded from.

We are working on this feature, will give update once we have something in this area.

**Comment by payman81** [comment]
This would be a nice feature. 
Certainly a good candidate for JustSaying 3.0.

**Comment by dariusdamalakas** [comment]
Hi, we have implemented this (not yet published to our fork). We have changed MessageSerializer so that it would have means to override the message type detection mechanism. This allowed us to pass full SQS message body to message serializer - in turn that allows to register custom serializators for SES delivery messages. These serializators then use a different logic to deserialize a message, i.e. handle the format that SES delivery messages are using. Everything else stays the same. Pretty useful.

I will update readme.md file and push code to our [repo](https://github.com/Intelliflo/JustSaying). Don't think we will be able to provide a PR for this because of outstanding issues (#77 and #79).

**Comment by dariusdamalakas** [comment]
@payman81 @brainmurphy  - PR is ready for this at 
[improved message serialiser fork](https://github.com/Intelliflo/JustSaying/tree/ImprovedMessageSerialiser).  Just need to get existing PR merged, as this is an incremental change.
