### ISSUE TITLE
Inconsisten behaviour: enum should always be serialized as strings

### ISSUE THREAD

**Issue by dariusdamalakas** [justeat/JustSaying#83]
Hi,

Messages are serialized differently when using SQS publisher instead of SNS publisher. [`SnsTopicBase`](https://github.com/justeat/JustSaying/blob/fcb9e827c52cf93560bd69ebadfb4a76cbfd4d15/JustSaying.AwsTools/SnsTopicBase.cs) finds a type serializer and uses that to serialize message. However, [`SqsPublisher`](https://github.com/justeat/JustSaying/blob/fcb9e827c52cf93560bd69ebadfb4a76cbfd4d15/JustSaying.AwsTools/SqsPublisher.cs) is using `JsonConvert.SerializeObject` to serialize message, and not message serializer.

**Comment by payman81** [comment]
Must use MessageSerializer and not JsonConvert.SerializeObject. Fancy sending a PR?

**Comment by dariusdamalakas** [comment]
>Must use MessageSerializer and not JsonConvert.SerializeObject
It has to use both. The reason is, when publishing a message onto SQS, SQS client sends the message as is, without any modifications. Not so for SNS client. When a message reaches topic, and then gets forwared to queue, a few extra properties/fields get added, namely the 'Subject' and 'Message'.  These have to be added manually by SqsPublisher. 

Also, we can not use`IMessageSerialiser` to serialize an anonymous object, because Serialize takes a Message parameter, and not `object`. So the minimal impact route is to just serialize message body with `TypeSerializer`, and then serialize again anonymous object with JsonConvert. 

>Fancy sending a PR?
#84

**Comment by payman81** [comment]
Merged your PR and updated Nuget. Thanks for the contribution.
