### ISSUE TITLE
Add support for SNS tagging

### ISSUE THREAD

**Issue by adammorr** [justeat/JustSaying#830]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Add configuration support for tagging topics

**Describe alternatives you've considered**
Manually tag topics

**Additional context**
This feels like an AWS feature which could be nicely exposed through the topic configuration API and potentially used in a myriad of ways by consumers.

* [TagResource action](https://docs.aws.amazon.com/sns/latest/api/API_TagResource.html)
* [.NET SDK](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=SNS/MSNSTagResourceTagResourceRequest.html)

**Comment by adammorr** [comment]
I'm going to pick this one up and see if I can get something suitable up for review

**Comment by gkinsman** [comment]
Nice! Keen to see what you come up with 👍

**Comment by adammorr** [comment]
PR raised https://github.com/justeat/JustSaying/pull/837

**Comment by adammorr** [comment]
#837 merged
