### ISSUE TITLE
Support publishing of Big Messages

### ISSUE THREAD

**Issue by maurofranchi** [justeat/JustSaying#889]
If an SNS/SQS message is too big to be published (`InvalidParameterException` exception from AWS Sdk), we should be able to guarantee that it gets published by storing the message to a different store (S3 maybe) and add the ARN of it to the message.
This can be either done by adding a `MessageLinkArn` to the base `Message` class or create a message attribute and let JustSaying Handlers to deserialise automatically the messages from S3 to the message object passed to the handler.

**Comment by gkinsman** [comment]
The advice we've come up internally for this is to use gzip on a case-by-case basis until we have a pressing use case that makes this necessary. In the meantime we'll investigate alternative serializers to make this easier to do.

Thanks for raising the issue!
