### ISSUE TITLE
Globally configure retention period and other queue parameters

### ISSUE THREAD

**Issue by dariusdamalakas** [justeat/JustSaying#92]
Hi,
The default way to override queue parameters is throught `ConfigureSubscriptionWith` as in.

````
CreateMeABus.InRegion(RegionEndpoint.EUWest1.SystemName)
             .WithSqsTopicSubscriber()
             .IntoQueue(queue2)
             .ConfigureSubscriptionWith(y =>
             {
                 y.MaxAllowedMessagesInFlight = 1;
             })
````

Now, I wonder would it be a good idea to update `JustSayingConstants` and instead of constants change default parameters to properties. This is a minimal change, no impact, but would allow us to change the defaults for subscribers in a global way. We have a scenario where we have tens of services, and now they all have a default parameters set to what is defined in `JustSayingConstants`. Now, without going to each of the service and updating it manually, which obviously would be a tedious and repetitive job, we would like to just update this globally. All of our services use an abstraction that we have built around JustSaying, so definitely this change would allow us to achieve this. 

Let me know what you guys think about it, happy to send a PR for this.

**Comment by payman81** [comment]
Sounds good. PR would be welcome.

**Comment by dariusdamalakas** [comment]
Super, thanks. Will do.

**Comment by dariusdamalakas** [comment]
#95
