### ISSUE TITLE
Message Attribute is not getting serialised in the message object. 

### ISSUE THREAD

**Issue by Pronoy999** [justeat/JustSaying#943]
**Describe the bug**
The Message Object contains a member called Message Attribute, which should contain the SQS Message attributes. 

**Expected behaviour**
The Message Object from the JustSaying Models should contain a Message Attribute. 

**Actual behaviour**
The Message Object from the JustSaying Models does not contain Message Attribute. 

**System information:**
 - OS: MacOS 11
 - Library Version 6.0.5
 - .NET version 5.0
 -

**Comment by martincostello** [comment]
Tracking documentation for this feature in #944.
