### ISSUE TITLE
Correlate messages across a distributed system

### ISSUE THREAD

**Issue by petemounce** [justeat/JustSaying#99]
I would like to have a way of knowing why a message was processed - where it originated from, which user at the application-layer caused that message to be published and consumed, and things like that. I tend to think of messages like deferred HTTP requests.

In the HTTP world, I'd be able to add headers to the request like `x-conversation` with some unique ID, that can then be harvested & passed through as work ripples around a distributed system. This is _really_ useful for tracing work and user journeys. I'm able to use the same mechanism to decide how to handle requests, for example if I'm A/B testing.

Having talked to @payman81, we think this is possible via something like
- JustSaying makes a message `Envelope` (analogous to an HTTP request body) a 1st-class citizen, and available to handlers when they process messages.
  - the envelope can basically expose the SQS metadata, which opens up a set of enhancements like being able to know dwell times of the underlying transport, how many attempts that the message has had by a given handler, and some other stuff
- To (try to) avoid a breaking change, we talked about introducing a base class for `Handler` with a virtual method that consumers can choose to override, or not, which has access to the `Envelope`, and can make decisions based on it.

**Comment by dariusdamalakas** [comment]
We solved this by just adding a `dict<string, string>` as the `Headers` property on the message, and added middleware to put correlation ids on the outgoing messages. If correlation ID exists on incoming message, we pass that through to outgoing messages. In fact, we have the same going on with HTTP requests, so we can track API requests and bus messages and correlate these. 

We should consider this carefully, but this might be a useful feature.

**Comment by petemounce** [comment]
@dariusdamalakas that sounds like what we want too. Do you have code to share?

**Comment by dariusdamalakas** [comment]
It's not trivial, as we've built a bus middleware concept around the `IHandler` interface, similar to what Owin gives with its middlewares, in a similar fashion with `app.Use(justSayingBusMiddleware)`. I can try and extract some of it into a gist to give an idea how we went around with it. I'd be happy to hear your thoughts whether any of it could be made generic enough to suite everyone.

**Comment by payman81** [comment]
@dariusdamalakas It would be great If you could send us a gist with your snippets. I think that's something people can benefit from.

**Comment by dariusdamalakas** [comment]
@payman81, here's the [gist  - bus middleware support](https://gist.github.com/dariusdamalakas/61918fc63b67ced322bf).  Apologies for that being explicitly verbose, but I wanted to show how we are using `JustEat`. I'll try to explain as much possible the key concepts we have introduced. Note that in any way I am not saying this is applicable to everyone, but some ideas i would like to see implemented in one way or another in JustSaying.

1. We use a autofac dependency injection. We needed a unit of work handler, where dependencies would be resolved once per message. 
1. Middleware support, similarly to what we have with the Owin pipeline. 
1. JustSaying handlers can be chained, but there is no way how to flow the context. We have introduced `IBusContext` which is passed to all middlewares and handlers.
1. In the [startup class](https://gist.github.com/dariusdamalakas/61918fc63b67ced322bf#file-busmiddlewaresupport-cs-L164) you can see how we set up the middlewares that will be used.
1. @petemounce , in the startup, we set up bus correlation middleware. This is what directly relates to your topic here. You put any context in bus headers - user id, current running service, correlation id, etc.
1. Added `IDictionary<string, string> Headers { get; set; }` to the message. 
1. [BusUnitOfWorkHandler](https://gist.github.com/dariusdamalakas/61918fc63b67ced322bf#file-busmiddlewaresupport-cs-L165) is the implementation of JustSaying handler, which internally pushes the message through the middleware pipeline, and handles the message. We could even add support for registering multiple handlers here, which is not supported by JustSaying out of the box.
1. [IBusPublisher](https://gist.github.com/dariusdamalakas/61918fc63b67ced322bf#file-busmiddlewaresupport-cs-L118) - this is a wrapper on top of JustSaying publisher, adds support for message mutators. You can look at this as the pipeline for the published messages.

I have added some extra in line comments to the code, so hopefully that will explain some bits. 

Hope this helps, comments and feedback more than welcome.
